import { getTableColumns, getTableName, is, type Table } from "drizzle-orm";
import { PgTable } from "drizzle-orm/pg-core";
import * as schema from "@/db/schema";

/**
 * The role the operator's read-only query door reads through, and the columns it may never see.
 *
 * Why a role at all. The door was written once as "`postgres` runs your select inside a read-only
 * transaction", and that was refused — rightly. A read of everything is also a write of nothing but
 * a theft of anything: `players.personal_token` is the credential behind `/p/{token}`, so whoever
 * can read it can sign in as that person. `push_subscriptions.endpoint` is a capability URL that
 * pushes to somebody's phone. `events.manage_code` is the organiser's own door. "Read-only" says
 * nothing about any of that.
 *
 * Filtering the answer cannot work either, and it is worth writing down why, because it is the
 * obvious idea: a redactor that drops a `personal_token` key from each row is defeated by
 * `select to_jsonb(p) from players p`, which carries the same value under a different key. The only
 * sound place to stop it is the database, before the row exists.
 *
 * So: `kicksmash_reader` is granted `select` **per column**, and never on a hidden one. A query that
 * names one is refused by Postgres, and so is `select *` on a table that has one — with an error
 * naming the column, which is a far better teacher than a silent blank. Tables with nothing hidden
 * keep `select *` working.
 */
export const READER_ROLE = "kicksmash_reader";

/**
 * Columns no reader may see, by exact name, in any table.
 *
 * Exact names rather than a pattern, because the patterns are wrong in both directions here:
 * `events.code` is the public share code that lives in every URL, while `events.manage_code` is the
 * organiser's secret; `metrics_daily.key` is the name of a metric and `api_keys.key_hash` is a
 * credential. `tests/readonly.test.ts` walks the real schema and fails when a new column looks like
 * a credential and appears on neither list, so the next token added cannot be forgotten.
 */
export const HIDDEN_COLUMNS: readonly string[] = [
  // Signs a person in on any device: /p/{token}
  "personal_token",
  "previous_token",
  // The organiser's door to a match, a club's to its page, a coach's student link
  "manage_code",
  "manager_code",
  "manage_token",
  "invite_code",
  // Claims a partner's place in a tournament pair
  "claim_token",
  // One-time login codes and API credentials, hashed — a six-digit hash is not a secret for long
  "code_hash",
  "key_hash",
  "secret",
  // A web-push subscription: the endpoint alone lets somebody push to that phone
  "endpoint",
  "p256dh",
  "auth",
];

/**
 * Names that read like a credential but are not, each checked once. The test treats anything
 * matching the same shapes and appearing on neither list as a new credential nobody reviewed.
 */
export const REVIEWED_SAFE: readonly string[] = [
  "code", // events, groups: the public 4-6 character code in the URL
  "key", // metrics_daily, research_runs: the name of a metric or a stored query
  "query_key",
  "thread_key",
  "hash", // research_cache: a hash of a search question, so the same question is not paid for twice
  "author", // listen_items: who wrote the article. Caught by the "auth" in it, which is the point
  "key_id", // webhooks: which api_keys row owns this hook, not the key itself
];

/** The shapes worth a second look. Used by the test, not by the grants. */
export const SUSPICIOUS = /(token|secret|hash|key|code|password|endpoint|p256dh|auth|credential)/i;

export const isHidden = (column: string): boolean => HIDDEN_COLUMNS.includes(column);

/** Every table the schema declares, with its SQL column names, sorted so the output never churns. */
export function schemaTables(): { table: string; columns: string[] }[] {
  return (Object.values(schema).filter((t) => is(t, PgTable)) as unknown as Table[])
    .map((t) => ({ table: getTableName(t), columns: Object.values(getTableColumns(t)).map((c) => c.name).sort() }))
    .sort((a, b) => a.table.localeCompare(b.table));
}

const ident = (s: string) => {
  if (!/^[a-z_][a-z0-9_]*$/.test(s)) throw new Error(`unquotable identifier: ${s}`);
  return `"${s}"`;
};

/**
 * The grants, as SQL. Regenerated by the test from the live schema and compared against the
 * migration on disk, so a new column cannot reach production without somebody deciding whether a
 * reader may see it.
 */
export function readerGrantsSql(): string {
  const lines: string[] = [
    `-- Generated from src/db/schema by src/lib/db/readonly.ts. Do not hand-edit: tests/readonly.test.ts compares the two.`,
    `do $$ begin if not exists (select 1 from pg_roles where rolname = '${READER_ROLE}') then create role ${ident(READER_ROLE)} nologin; end if; end $$;`,
    `grant ${ident(READER_ROLE)} to current_user;`,
    `revoke all on all tables in schema public from ${ident(READER_ROLE)};`,
    `grant usage on schema public to ${ident(READER_ROLE)};`,
  ];
  for (const { table, columns } of schemaTables()) {
    const visible = columns.filter((c) => !isHidden(c));
    if (visible.length === 0) continue;
    lines.push(`grant select (${visible.map(ident).join(", ")}) on public.${ident(table)} to ${ident(READER_ROLE)};`);
  }
  // Drizzle's migrator splits a file on this marker, and a `do $$ … $$` block carries its own
  // semicolons, so the marker is the only safe separator.
  return lines.join("\n--> statement-breakpoint\n") + "\n";
}
