import { calendarTitle } from "@/lib/calendar";
import { formatEventDay, formatEventTime } from "@/lib/dates";
import { isOccupied } from "@/lib/domain/events";
import { formatLevel, formatRange, hasRange } from "@/lib/domain/levels";
import type { EventDetail } from "@/lib/domain/queries";
import { lineupComplete } from "@/lib/lineup";
import { esc, miniAppUrl, type InlineKeyboard } from "./api";

export type BotLocale = "en" | "ru" | "es";
export const botLocale = (languageCode: string | null | undefined): BotLocale => {
  const c = languageCode?.toLowerCase() ?? "";
  return c.startsWith("ru") ? "ru" : c.startsWith("es") ? "es" : "en";
};

/** Bot copy lives here on purpose: short, two languages, no framework. */
const STRINGS = {
  en: {
    match: "Padel match",
    tournament: "Padel tournament",
    formatMexicano: "Mexicano",
    formatKing: "King of the court",
    formatAmericano: "Americano",
    courtTbd: "Court TBD",
    court: (n: string) => `Court ${n}`,
    level: "Level",
    players: "Players",
    reserved: "reserved",
    organizer: "org",
    waitlist: (n: number) => `Waitlist: ${n}`,
    spots: (n: number) => (n === 1 ? "1 spot left" : `${n} spots left`),
    full: "Full · waitlist open",
    closed: "Full",
    complete: "Line-up complete ✓",
    cancelled: "Cancelled",
    past: "Played",
    in: "✅ I'm in",
    out: "❌ Can't make it",
    open: "Open",
    toastJoined: "You're in ✅",
    toastWaitlisted: "Full for now. You're on the waitlist.",
    toastAlready: "You're already in.",
    toastLeft: "Taken you out of the match.",
    toastNotIn: "You weren't in this match.",
    toastLevel: "This match has a level range. Open it once to set your level.",
    toastRequested: "Outside the level range: the organizer will approve.",
    toastClosed: "The match is full and closed.",
    toastPast: "This match is over.",
    toastError: "Something went wrong. Open the match instead.",
    welcome: "Hi. I keep one card per match here and stay quiet otherwise: people join with one tap, the card updates itself. Type /new and pick a day, a time and a place, or write it in one line: /new tomorrow 19:00 Rawai. Paste a kicksma.sh link and I turn it into a card.",
    newWhen: "New match. When?",
    newTime: "What time?",
    newWhere: "Where?",
    newZone: "Which city is this chat in? Once; /tz changes it later.",
    newTip: "Tip: one line does it all: /new tomorrow 19:00 Rawai",
    newReplyTime: "Another time: reply to this message with it, e.g. 18:30.",
    newReplyPlace: "Another place: reply to this message with its name.",
    today: "Today",
    tomorrow: "Tomorrow",
    formBtn: "Full form ↗",
    newMatch: "Create the match here (ten seconds). The card lands in this chat:",
    help: "/new: a match in three taps, or in one line: /new tomorrow 19:00 Rawai\n/match CODE posts the card of an existing match\n/score CODE 6-3 6-4 after a match\n/games: open matches near you\n/tz and /lang: this chat's time zone and my language\n/feedback: what should change\nIn a chat with other bots, pick commands from the menu or add @kicksmash_bot, or write to me privately.\nEverything else: one tap on the card.",
    completeNote: (n: number, time: string) => `Line-up complete ✓ ${n} players. See you at ${time}.`,
    reminder: (title: string, where: string, n: number, cap: number) => `⏰ In about an hour: ${title} · ${where}. ${n}/${cap} players.`,
    result: "🏁 Result",
    winner: (names: string) => `🏆 ${names}`,
    privateStart: (url: string) => `Your personal page: ${url}\nIt lists your matches and signs you in on any device.`,
    langSet: "Language: English",
    notHere: "I only work inside group chats and via the buttons. Add me to your padel chat.",
    noMatch: "No match with that code.",
    discordHelp: "/new creates a match for this channel\n/match CODE posts the card of an existing match\n/ask a padel or Kicksmash question\n/lang switches my language\nEverything else: one tap on the card. I also answer questions people ask here, about once an hour.",
    posted: "Card posted.",
    thinking: "Thinking…",
    noAnswer: "I don't have a good answer to that one. Try asking in more detail, or open kicksma.sh/answers.",
    changedNote: (title: string, when: string, where: string) => `🔁 ${title}: now ${when} · ${where}.`,
    cancelledNote: (title: string, when: string) => `❌ ${title} on ${when} is cancelled.`,
    wantHow: "Tell me when you want to play and I will say so when a match turns up: /want tue 14 Rawai Padel. A day, an hour and a place — anything but the place can be left out.",
    wantSaved: (when: string, place: string) => `Saved: ${when} at ${place}. I will tell you when a match fits, and a spot that opens comes to you first. /want on its own shows your list.`,
    wantNone: "You have not told me when you want to play. Try: /want tue 14 Rawai Padel.",
    wantList: (list: string) => `You are waiting for:\n${list}\nAdd another with /want tue 14 <place>, or tap one to remove it.`,
    wantUnknownPlace: "I do not know that court yet. Try the city: /want tue 14 Phuket.",
    wantTooMany: "Ten is the most at once. Remove one first with /want.",
    wantRemoved: "Removed.",
    wantAnyDay: "Any day",
    wantAnyTime: "any time",
    // The player's keyboard under the text field: every door a tap.
    menuFind: "🔎 Find a match",
    menuMine: "📅 My matches",
    menuNew: "➕ New match",
    menuWant: "🕒 When I want to play",
    menuCoach: "🎾 Coach me",
    menuHelp: "❓ Help",
    menuPlayer: "Everything here is a tap: find a match near you, see yours, make one, or say when you want to play and I will tell you when a match fits.",
    menuPlaceholderPlayer: "Tap a button",
    gamesPickCity: "Which city?",
    gamesMineNone: "No upcoming matches. Find one, or make one.",
    wantDay: "When do you want to play? Pick a day.",
    wantHour: "From what time?",
    wantPlace: "Where?",
    wantCity: (name: string) => `Anywhere in ${name}`,
    linkedPlayer: "Telegram is on: your matches, your reminders and your results come here now.",
    studentJoined: (coach: string) => `You're on ${coach}'s list: book, move and pay here, with the buttons below.`,
    studentLinkBad: "This invite is not valid any more. Ask your coach for a fresh one.",
    claimDone: (category: string, p1: string) => `Confirmed: you play ${category} with ${p1}. Your matches and their times come here.`,
    claimBad: "This link was used already, or the pair withdrew.",
    bindBad: "This link is too old. Open a newer email from Kicksmash, or sign in on the site and tap Telegram there.",
    map: "📍 Map",
    // Tournaments in the chat: the open ones as buttons, a category's door, the partner by name.
    menuTournaments: "🏆 Tournaments",
    tournamentsNone: (url: string) => `No open tournaments right now. The list, and yours to make: ${url}`,
    tournamentsPick: "Open tournaments. Tap one.",
    tournamentPairs: (n: number, max: number | null) => (max ? `${n}/${max} pairs` : `${n} pairs`),
    tournamentWaiting: (n: number) => `${n} waiting`,
    tournamentEnter: (category: string) => `Enter ${category}`,
    tournamentClosed: "Entries closed",
    tournamentPartnerAsk: (category: string) => `${category}: your partner's name? Reply to this message with it.`,
    tournamentEntered: (category: string, partner: string) => `You are in ${category} with ${partner}.`,
    tournamentWaitlisted: (category: string, partner: string, n: number) => `${category} is full. You and ${partner} are number ${n} on the waiting list.`,
    tournamentPartnerLink: (link: string) => `Send this to your partner; one tap confirms the spot:\n${link}`,
    tournamentMine: (list: string) => `Your entries:\n${list}`,
    tournamentErr: (code: string) =>
      code === "closed" ? "Entries are closed for this category." : code === "already_in" ? "One of you is already in this category." : code === "too_many" ? "Two categories per person is the most." : code === "level" ? "Your level is outside this category's band. Set it on the site first." : code === "same_player" ? "That is you. Name your partner." : "Something went wrong. Open the tournament on the site instead.",
    newHowTo: "I did not catch a time. One line does it: /new tomorrow 19:00 Rawai (cost and level are optional: /new sat 10:00 Bangtao 400฿ level 3-4). Or just type /new and tap.",
    needTz: "Which time zone is this chat in? Once: /tz phuket (a city or a zone name). Or use the form:",
    tzSet: (tz: string) => `Time zone for this chat: ${tz}.`,
    tzUnknown: "I don't know that zone. Try a city (/tz phuket) or a zone name (/tz Asia/Bangkok).",
    newPast: "That was more than a day ago. For a match you already played, give today's or yesterday's date.",
    tooMany: "That is a lot of matches for one day. Try again tomorrow.",
    resultBtn: "🏁 Result",
    didntPlayBtn: "We didn't play",
    toastDidntPlay: "Marked as cancelled. Nobody is asked for a score.",
    didntPlayDone: (title: string) => `${title}: marked as not played. Nobody is asked for a score.`,
    toastNotOrganizer: "Only the organizer can do that.",
    whoWon: (title: string) => `${title}: who won?`,
    notYet: "The match hasn't started yet.",
    needFour: "The result needs four players in the line-up.",
    /** The same, in the player's own chat, where the score form comes with it as the 🏁 button. */
    needFourPage: "In the chat a result needs four players. The match page takes any line-up: tap 🏁 Result below.",
    onlyPlayers: "Only players in this match can enter the result.",
    onlyOrganizer: "Only the organizer can confirm.",
    resultLocked: "The organizer already confirmed the result.",
    recorded: (winners: string, by: string) => `🏆 ${winners}\nRecorded by ${by}. Organizer: confirm below, or tap again to correct.`,
    confirmBtn: "✔ Confirm",
    confirmedNote: (winners: string) => `🏆 ${winners} · confirmed ✓`,
    scoreHint: (code: string) => `Sets, if you like: /score ${code} 6-3 6-4`,
    scoreHow: "Like this: /score CODE 6-3 6-4 (or reply to the card with /score 6-3 6-4).",
    scoreNoTeams: "Tap 🏁 Result on the card first, so I know the teams.",
    noTeamsPage: "I don't know the pairs yet. Tap 🏁 Result below to enter the score on the match page.",
    scoreSaved: (score: string) => `Saved: ${score}`,
    sameTime: "🔁 Same time next week?",
    groupMade: (name: string, when: string) => `Done: “${name}”. Every ${when} a fresh card posts itself here; members tap in or out.`,
    groupExists: (name: string) => `This crew is already a group: “${name}”.`,
    onlyPlayersGroup: "Only players in this match can start the group.",
    scoreNudge: (title: string) => `${title}: how did it go? Reply with the score, like 6-4 6-3, or tap 🏁.`,
    /** Somebody else answered first. Said to a tap that raced the edit, and as the edit itself. */
    scoreAlready: (who: string | null, score: string) => (who ? `${who} already added the score: ${score}` : `The score is already in: ${score}`),
    /** Under the result card the nudge turned into: who put the score there. */
    scoreBy: (who: string) => `Entered by ${who}`,
    /** The one button under that card: its page, where the court photo goes on and the picture goes to WhatsApp. */
    cardBtn: "📸 Photo & share",
    feedbackAdded: "Added to your note, thank you.",
    toastSaved: "Saved ✅",
    share: "📤 Share",
    privateHelp: "Here you can also:\n/new tomorrow 19:00 Rawai creates a match; share its card into any chat with 📤\n/games shows open matches near you (add a city: /games phuket)\nPaste a kicksma.sh link or a code and I show the card.\n/coach: your lessons book, if you coach (students book themselves, packages count themselves).",
    coachLink: "Your assistant: students book available times themselves, packages count themselves, every reschedule happens while you coach. Open it here; setup takes a minute.",
    coachOpen: "Open my assistant",
    coachLinkExpired: "That link has expired. Open kicksma.sh/coach and tap the button again.",
    coachLinkOther: "This assistant is already linked to another Telegram account.",
    gamesTitle: (city: string) => `Open matches · ${city}`,
    gamesMine: "Your upcoming matches",
    gamesNone: (city: string) => `No open matches listed in ${city} right now. Create one: /new tomorrow 19:00 <club>.`,
    gamesWhichCity: "Which city? /games phuket or /games singapore.",
    inlineNothing: "No matches to share yet. Create one in a chat with me: /new tomorrow 19:00 <club>.",
    inlineHint: "Create a match",
    spotsShort: (n: number, cap: number) => `${n}/${cap}`,
    orgNote: (kind: string, name: string, n: number, cap: number) =>
      kind === "joined" ? `✅ ${name} is in · ${n}/${cap}` : kind === "waitlisted" ? `⏳ ${name} joined the waitlist` : kind === "left" ? `↩️ ${name} left · ${n}/${cap}` : kind === "requested" ? `🙋 ${name} asks to join (outside the level range)` : kind === "confirmed" ? `✅ ${name} confirmed · ${n}/${cap}` : kind === "declined" ? `❌ ${name} declined` : `⬆️ ${name} moved in from the waitlist · ${n}/${cap}`,
  },
  ru: {
    match: "Падел-матч",
    tournament: "Падел-турнир",
    formatMexicano: "Мексикано",
    formatKing: "Король корта",
    formatAmericano: "Американо",
    courtTbd: "Корт уточняется",
    court: (n: string) => `Корт ${n}`,
    level: "Уровень",
    players: "Игроки",
    reserved: "бронь",
    organizer: "орг",
    waitlist: (n: number) => `Лист ожидания: ${n}`,
    spots: (n: number) => `Свободно: ${n}`,
    full: "Мест нет · лист ожидания открыт",
    closed: "Мест нет",
    complete: "Состав собран ✓",
    cancelled: "Отменён",
    past: "Сыгран",
    in: "✅ Играю",
    out: "❌ Не смогу",
    open: "Открыть",
    toastJoined: "Вы в игре ✅",
    toastWaitlisted: "Пока мест нет. Вы в листе ожидания.",
    toastAlready: "Вы уже записаны.",
    toastLeft: "Вы вышли из матча.",
    toastNotIn: "Вы не были записаны.",
    toastLevel: "У матча есть диапазон уровней. Откройте его один раз и укажите свой уровень.",
    toastRequested: "Вне диапазона уровней: организатор подтвердит.",
    toastClosed: "Матч заполнен и закрыт.",
    toastPast: "Матч уже прошёл.",
    toastError: "Что-то пошло не так. Откройте матч.",
    welcome: "Привет. Я веду одну карточку на матч и больше не пишу: люди записываются одним нажатием, карточка обновляется сама. Напишите /new и выберите день, время и место, или всё одной строкой: /new завтра 19:00 Равай. Вставьте ссылку kicksma.sh, и я превращу её в карточку.",
    newWhen: "Новый матч. Когда?",
    newTime: "Во сколько?",
    newWhere: "Где?",
    newZone: "В каком городе этот чат? Один раз; /tz поменяет.",
    newTip: "Совет: всё одной строкой: /new завтра 19:00 Равай",
    newReplyTime: "Другое время: ответьте на это сообщение, например 18:30.",
    newReplyPlace: "Другое место: ответьте на это сообщение его названием.",
    today: "Сегодня",
    tomorrow: "Завтра",
    formBtn: "Полная форма ↗",
    newMatch: "Создайте матч здесь (десять секунд). Карточка появится в этом чате:",
    help: "/new: матч в три нажатия или одной строкой: /new завтра 19:00 Равай\n/match КОД публикует карточку существующего матча\n/score КОД 6-3 6-4 после матча\n/games: открытые матчи рядом\n/tz и /lang: часовой пояс чата и мой язык\n/feedback: что стоит изменить\nВ чате с другими ботами выбирайте команды из меню или добавляйте @kicksmash_bot, либо напишите мне лично.\nВсё остальное: одно нажатие на карточке.",
    completeNote: (n: number, time: string) => `Состав собран ✓ ${n} игроков. До встречи в ${time}.`,
    reminder: (title: string, where: string, n: number, cap: number) => `⏰ Примерно через час: ${title} · ${where}. Игроков: ${n}/${cap}.`,
    result: "🏁 Результат",
    winner: (names: string) => `🏆 ${names}`,
    privateStart: (url: string) => `Ваша личная страница: ${url}\nТам все ваши матчи, и она же вход с любого устройства.`,
    langSet: "Язык: русский",
    notHere: "Я работаю в групповых чатах и через кнопки. Добавьте меня в чат вашей падел-компании.",
    noMatch: "Матча с таким кодом нет.",
    discordHelp: "/new создаёт матч для этого канала\n/match КОД публикует карточку существующего матча\n/ask вопрос о паделе или Kicksmash\n/lang меняет язык\nВсё остальное: одно нажатие на карточке. Я также отвечаю на вопросы в канале, примерно раз в час.",
    posted: "Карточка опубликована.",
    thinking: "Думаю…",
    noAnswer: "Хорошего ответа у меня нет. Спросите подробнее или загляните на kicksma.sh/answers.",
    changedNote: (title: string, when: string, where: string) => `🔁 ${title}: теперь ${when} · ${where}.`,
    cancelledNote: (title: string, when: string) => `❌ ${title} ${when} отменён.`,
    wantHow: "Скажите, когда хотите играть, и я сообщу, когда появится матч: /want вт 14 Rawai Padel. День, час и место — всё, кроме места, можно опустить.",
    wantSaved: (when: string, place: string) => `Сохранил: ${when} на ${place}. Сообщу, когда появится подходящий матч, а освободившееся место придёт к вам первым. /want без слов покажет список.`,
    wantNone: "Вы не сказали, когда хотите играть. Например: /want вт 14 Rawai Padel.",
    wantList: (list: string) => `Вы ждёте:\n${list}\nДобавить ещё: /want вт 14 <место>, или нажмите, чтобы удалить.`,
    wantUnknownPlace: "Такой корт мне пока не знаком. Попробуйте город: /want вт 14 Пхукет.",
    wantTooMany: "Больше десяти сразу нельзя. Сначала удалите одну через /want.",
    wantRemoved: "Удалено.",
    wantAnyDay: "Любой день",
    menuFind: "🔎 Найти матч",
    menuMine: "📅 Мои матчи",
    menuNew: "➕ Новый матч",
    menuWant: "🕒 Когда хочу играть",
    menuCoach: "🎾 Тренер",
    menuHelp: "❓ Помощь",
    menuPlayer: "Здесь всё одним нажатием: найти матч рядом, посмотреть свои, создать новый или сказать, когда хотите играть, — и я сообщу, когда появится подходящий матч.",
    menuPlaceholderPlayer: "Нажмите кнопку",
    gamesPickCity: "Какой город?",
    gamesMineNone: "Предстоящих матчей нет. Найдите или создайте.",
    wantDay: "Когда хотите играть? Выберите день.",
    wantHour: "С какого времени?",
    wantPlace: "Где?",
    wantCity: (name: string) => `Где угодно в ${name}`,
    linkedPlayer: "Telegram подключён: матчи, напоминания и результаты теперь приходят сюда.",
    studentJoined: (coach: string) => `Вы в списке ${coach}: записывайтесь, переносите и платите здесь, кнопками ниже.`,
    studentLinkBad: "Это приглашение больше не действует. Попросите у тренера новое.",
    claimDone: (category: string, p1: string) => `Подтверждено: вы играете ${category} с ${p1}. Матчи и их время придут сюда.`,
    claimBad: "Ссылка уже использована, или пара снялась.",
    bindBad: "Эта ссылка устарела. Откройте более новое письмо от Kicksmash или войдите на сайте и нажмите Telegram там.",
    map: "📍 Карта",
    menuTournaments: "🏆 Турниры",
    tournamentsNone: (url: string) => `Открытых турниров сейчас нет. Список и свой турнир: ${url}`,
    tournamentsPick: "Открытые турниры. Нажмите на один.",
    tournamentPairs: (n: number, max: number | null) => (max ? `${n}/${max} пар` : `${n} пар`),
    tournamentWaiting: (n: number) => `${n} в ожидании`,
    tournamentEnter: (category: string) => `Заявиться: ${category}`,
    tournamentClosed: "Заявки закрыты",
    tournamentPartnerAsk: (category: string) => `${category}: имя вашего партнёра? Ответьте на это сообщение.`,
    tournamentEntered: (category: string, partner: string) => `Вы в ${category} с ${partner}.`,
    tournamentWaitlisted: (category: string, partner: string, n: number) => `${category}: мест нет. Вы и ${partner} — номер ${n} в листе ожидания.`,
    tournamentPartnerLink: (link: string) => `Отправьте партнёру; одно нажатие подтверждает место:\n${link}`,
    tournamentMine: (list: string) => `Ваши заявки:\n${list}`,
    tournamentErr: (code: string) =>
      code === "closed" ? "Заявки в эту категорию закрыты." : code === "already_in" ? "Один из вас уже в этой категории." : code === "too_many" ? "Не больше двух категорий на человека." : code === "level" ? "Ваш уровень вне диапазона категории. Сначала укажите его на сайте." : code === "same_player" ? "Это вы. Назовите партнёра." : "Что-то пошло не так. Откройте турнир на сайте.",
    wantAnyTime: "в любое время",
    newHowTo: "Не нашёл время. Одной строкой: /new завтра 19:00 Равай (цена и уровень по желанию: /new сб 10:00 Бангтао 400฿ уровень 3-4). Или просто /new и нажимайте.",
    needTz: "В каком часовом поясе этот чат? Один раз: /tz пхукет (город или название зоны). Или через форму:",
    tzSet: (tz: string) => `Часовой пояс чата: ${tz}.`,
    tzUnknown: "Не знаю такой зоны. Попробуйте город (/tz пхукет) или название зоны (/tz Asia/Bangkok).",
    newPast: "Это больше суток назад. Для уже сыгранного матча укажите сегодняшнюю или вчерашнюю дату.",
    tooMany: "Слишком много матчей за день. Попробуйте завтра.",
    resultBtn: "🏁 Результат",
    didntPlayBtn: "Мы не играли",
    toastDidntPlay: "Отмечено как отменённый. Счёт никто не спросит.",
    didntPlayDone: (title: string) => `${title}: отмечено как несыгранный. Счёт никто не спросит.`,
    toastNotOrganizer: "Это может сделать только организатор.",
    whoWon: (title: string) => `${title}: кто выиграл?`,
    notYet: "Матч ещё не начался.",
    needFour: "Для результата нужны четыре игрока в составе.",
    needFourPage: "В чате для результата нужны четыре игрока. На странице матча подойдёт любой состав: нажмите 🏁 Результат ниже.",
    onlyPlayers: "Результат могут вносить только участники матча.",
    onlyOrganizer: "Подтвердить может только организатор.",
    resultLocked: "Организатор уже подтвердил результат.",
    recorded: (winners: string, by: string) => `🏆 ${winners}\nВнёс(ла): ${by}. Организатор: подтвердите ниже или нажмите ещё раз, чтобы исправить.`,
    confirmBtn: "✔ Подтвердить",
    confirmedNote: (winners: string) => `🏆 ${winners} · подтверждено ✓`,
    scoreHint: (code: string) => `Счёт по сетам, если хотите: /score ${code} 6-3 6-4`,
    scoreHow: "Вот так: /score КОД 6-3 6-4 (или ответом на карточку: /score 6-3 6-4).",
    scoreNoTeams: "Сначала нажмите 🏁 Результат на карточке, чтобы я знал составы пар.",
    noTeamsPage: "Я пока не знаю составы пар. Нажмите 🏁 Результат ниже, чтобы ввести счёт на странице матча.",
    scoreSaved: (score: string) => `Сохранено: ${score}`,
    sameTime: "🔁 В то же время на следующей неделе?",
    groupMade: (name: string, when: string) => `Готово: «${name}». Каждый ${when} здесь сама появляется новая карточка; участники нажимают «в игре» или «пас».`,
    groupExists: (name: string) => `Эта компания уже группа: «${name}».`,
    onlyPlayersGroup: "Создать группу могут только игроки этого матча.",
    scoreNudge: (title: string) => `${title}: как сыграли? Ответьте счётом, например 6-4 6-3, или нажмите 🏁.`,
    scoreAlready: (who: string | null, score: string) => (who ? `${who} уже внёс(ла) счёт: ${score}` : `Счёт уже внесён: ${score}`),
    scoreBy: (who: string) => `Счёт внёс(ла) ${who}`,
    cardBtn: "📸 Фото и поделиться",
    feedbackAdded: "Добавил к вашей заметке, спасибо.",
    toastSaved: "Сохранено ✅",
    share: "📤 Поделиться",
    privateHelp: "Здесь тоже можно:\n/new завтра 19:00 Равай создаёт матч; карточку можно отправить в любой чат через 📤\n/games показывает открытые матчи рядом (с городом: /games пхукет)\nВставьте ссылку kicksma.sh или код, и я покажу карточку\n/coach: ваша книга занятий, если вы тренер (ученики записываются сами, абонементы считаются сами).",
    coachLink: "Ваш ассистент: ученики сами записываются на доступное время, абонементы считаются сами, все переносы — пока вы тренируете. Откройте здесь; настройка за минуту.",
    coachOpen: "Открыть ассистента",
    coachLinkExpired: "Эта ссылка устарела. Откройте kicksma.sh/coach и нажмите кнопку ещё раз.",
    coachLinkOther: "Этот ассистент уже связан с другим аккаунтом Telegram.",

    gamesTitle: (city: string) => `Открытые матчи · ${city}`,
    gamesMine: "Ваши ближайшие матчи",
    gamesNone: (city: string) => `Сейчас в ${city} нет открытых матчей. Создайте: /new завтра 19:00 <клуб>.`,
    gamesWhichCity: "Какой город? /games пхукет или /games сингапур.",
    inlineNothing: "Пока нечего отправлять. Создайте матч в чате со мной: /new завтра 19:00 <клуб>.",
    inlineHint: "Создать матч",
    spotsShort: (n: number, cap: number) => `${n}/${cap}`,
    orgNote: (kind: string, name: string, n: number, cap: number) =>
      kind === "joined" ? `✅ ${name} играет · ${n}/${cap}` : kind === "waitlisted" ? `⏳ ${name} в листе ожидания` : kind === "left" ? `↩️ ${name} больше не играет · ${n}/${cap}` : kind === "requested" ? `🙋 ${name} просится в матч (вне диапазона уровней)` : kind === "confirmed" ? `✅ ${name}: участие подтверждено · ${n}/${cap}` : kind === "declined" ? `❌ ${name}: отказ` : `⬆️ ${name} из листа ожидания в состав · ${n}/${cap}`,
  },
  es: {
    match: "Partido de pádel",
    tournament: "Torneo de pádel",
    formatMexicano: "Mexicano",
    formatKing: "Rey de la pista",
    formatAmericano: "Americano",
    courtTbd: "Pista por confirmar",
    court: (n: string) => `Pista ${n}`,
    level: "Nivel",
    players: "Jugadores",
    reserved: "reservado",
    organizer: "org",
    waitlist: (n: number) => `Lista de espera: ${n}`,
    spots: (n: number) => (n === 1 ? "Queda 1 plaza" : `Quedan ${n} plazas`),
    full: "Completo · lista de espera abierta",
    closed: "Completo",
    complete: "Equipo completo ✓",
    cancelled: "Cancelado",
    past: "Jugado",
    in: "✅ Me apunto",
    out: "❌ No puedo",
    open: "Abrir",
    toastJoined: "Estás dentro ✅",
    toastWaitlisted: "Completo por ahora. Estás en la lista de espera.",
    toastAlready: "Ya estás dentro.",
    toastLeft: "Te he quitado del partido.",
    toastNotIn: "No estabas en este partido.",
    toastLevel: "Este partido tiene un rango de nivel. Ábrelo una vez para poner tu nivel.",
    toastRequested: "Fuera del rango de nivel: el organizador lo aprobará.",
    toastClosed: "El partido está completo y cerrado.",
    toastPast: "Este partido ya terminó.",
    toastError: "Algo salió mal. Abre el partido.",
    welcome: "Hola. Aquí mantengo una tarjeta por partido y me callo el resto del tiempo: la gente se apunta con un toque y la tarjeta se actualiza sola. Escribe /new y elige día, hora y lugar, o ponlo en una línea: /new mañana 19:00 Rawai. Pega un enlace de kicksma.sh y lo convierto en tarjeta.",
    newWhen: "Partido nuevo. ¿Cuándo?",
    newTime: "¿A qué hora?",
    newWhere: "¿Dónde?",
    newZone: "¿En qué ciudad está este chat? Una vez; /tz lo cambia después.",
    newTip: "Truco: una línea lo hace todo: /new mañana 19:00 Rawai",
    newReplyTime: "Otra hora: responde a este mensaje con ella, p. ej. 18:30.",
    newReplyPlace: "Otro lugar: responde a este mensaje con su nombre.",
    today: "Hoy",
    tomorrow: "Mañana",
    formBtn: "Formulario completo ↗",
    newMatch: "Crea el partido aquí (diez segundos). La tarjeta cae en este chat:",
    help: "/new: un partido en tres toques, o en una línea: /new mañana 19:00 Rawai\n/match CÓDIGO publica la tarjeta de un partido existente\n/score CÓDIGO 6-3 6-4 después de un partido\n/games: partidos abiertos cerca de ti\n/tz y /lang: la zona horaria de este chat y mi idioma\n/feedback: qué debería cambiar\nEn un chat con otros bots, elige los comandos del menú o añade @kicksmash_bot, o escríbeme en privado.\nTodo lo demás: un toque en la tarjeta.",
    completeNote: (n: number, time: string) => `Equipo completo ✓ ${n} jugadores. Nos vemos a las ${time}.`,
    reminder: (title: string, where: string, n: number, cap: number) => `⏰ En una hora aproximadamente: ${title} · ${where}. ${n}/${cap} jugadores.`,
    result: "🏁 Resultado",
    winner: (names: string) => `🏆 ${names}`,
    privateStart: (url: string) => `Tu página personal: ${url}\nTiene tus partidos y te da acceso desde cualquier dispositivo.`,
    langSet: "Idioma: español",
    notHere: "Solo trabajo dentro de chats de grupo y con los botones. Añádeme a tu chat de pádel.",
    noMatch: "No hay ningún partido con ese código.",
    discordHelp: "/new crea un partido para este canal\n/match CÓDIGO publica la tarjeta de un partido existente\n/ask una pregunta de pádel o de Kicksmash\n/lang cambia mi idioma\nTodo lo demás: un toque en la tarjeta. También respondo a las preguntas que se hacen aquí, más o menos una vez por hora.",
    posted: "Tarjeta publicada.",
    thinking: "Pensando…",
    noAnswer: "No tengo una buena respuesta para eso. Pregunta con más detalle, o abre kicksma.sh/answers.",
    changedNote: (title: string, when: string, where: string) => `🔁 ${title}: ahora ${when} · ${where}.`,
    cancelledNote: (title: string, when: string) => `❌ ${title} del ${when} está cancelado.`,
    wantHow: "Dime cuándo quieres jugar y te avisaré cuando aparezca un partido: /want mar 14 Rawai Padel. Un día, una hora y un lugar; todo menos el lugar se puede omitir.",
    wantSaved: (when: string, place: string) => `Guardado: ${when} en ${place}. Te avisaré cuando encaje un partido, y una plaza que se libere te llega primero. /want a secas muestra tu lista.`,
    wantNone: "No me has dicho cuándo quieres jugar. Prueba: /want mar 14 Rawai Padel.",
    wantList: (list: string) => `Estás esperando:\n${list}\nAñade otro con /want mar 14 <lugar>, o toca uno para quitarlo.`,
    wantUnknownPlace: "Todavía no conozco esa pista. Prueba con la ciudad: /want mar 14 Phuket.",
    wantTooMany: "Diez es el máximo a la vez. Quita uno primero con /want.",
    wantRemoved: "Quitado.",
    wantAnyDay: "Cualquier día",
    wantAnyTime: "a cualquier hora",
    menuFind: "🔎 Buscar partido",
    menuMine: "📅 Mis partidos",
    menuNew: "➕ Partido nuevo",
    menuWant: "🕒 Cuándo quiero jugar",
    menuCoach: "🎾 Entrenador",
    menuHelp: "❓ Ayuda",
    menuPlayer: "Aquí todo es un toque: busca un partido cerca, mira los tuyos, crea uno, o di cuándo quieres jugar y te avisaré cuando encaje un partido.",
    menuPlaceholderPlayer: "Toca un botón",
    gamesPickCity: "¿Qué ciudad?",
    gamesMineNone: "No tienes partidos próximos. Busca uno, o crea uno.",
    wantDay: "¿Cuándo quieres jugar? Elige un día.",
    wantHour: "¿Desde qué hora?",
    wantPlace: "¿Dónde?",
    wantCity: (name: string) => `En cualquier sitio de ${name}`,
    linkedPlayer: "Telegram activado: tus partidos, recordatorios y resultados llegan aquí desde ahora.",
    studentJoined: (coach: string) => `Estás en la lista de ${coach}: reserva, mueve y paga aquí, con los botones de abajo.`,
    studentLinkBad: "Esta invitación ya no es válida. Pide otra a tu entrenador.",
    claimDone: (category: string, p1: string) => `Confirmado: juegas ${category} con ${p1}. Tus partidos y sus horas llegan aquí.`,
    claimBad: "Este enlace ya se usó, o la pareja se retiró.",
    bindBad: "Este enlace es demasiado antiguo. Abre un correo más reciente de Kicksmash, o entra en el sitio y toca Telegram allí.",
    map: "📍 Mapa",
    menuTournaments: "🏆 Torneos",
    tournamentsNone: (url: string) => `No hay torneos abiertos ahora mismo. La lista, y el tuyo por crear: ${url}`,
    tournamentsPick: "Torneos abiertos. Toca uno.",
    tournamentPairs: (n: number, max: number | null) => (max ? `${n}/${max} parejas` : `${n} parejas`),
    tournamentWaiting: (n: number) => `${n} en espera`,
    tournamentEnter: (category: string) => `Inscribirse: ${category}`,
    tournamentClosed: "Inscripciones cerradas",
    tournamentPartnerAsk: (category: string) => `${category}: ¿el nombre de tu pareja? Responde a este mensaje.`,
    tournamentEntered: (category: string, partner: string) => `Estás en ${category} con ${partner}.`,
    tournamentWaitlisted: (category: string, partner: string, n: number) => `${category} está completo. Tú y ${partner} sois el número ${n} en la lista de espera.`,
    tournamentPartnerLink: (link: string) => `Envía esto a tu pareja; un toque confirma la plaza:\n${link}`,
    tournamentMine: (list: string) => `Tus inscripciones:\n${list}`,
    tournamentErr: (code: string) =>
      code === "closed" ? "Las inscripciones de esta categoría están cerradas." : code === "already_in" ? "Uno de los dos ya está en esta categoría." : code === "too_many" ? "Dos categorías por persona es el máximo." : code === "level" ? "Tu nivel está fuera del rango de esta categoría. Ponlo primero en el sitio." : code === "same_player" ? "Ese eres tú. Di el nombre de tu pareja." : "Algo salió mal. Abre el torneo en el sitio.",
    newHowTo: "No he visto una hora. Una línea basta: /new mañana 19:00 Rawai (precio y nivel son opcionales: /new sáb 10:00 Bangtao 400฿ nivel 3-4). O escribe /new y toca.",
    needTz: "¿En qué zona horaria está este chat? Una vez: /tz phuket (una ciudad o el nombre de la zona). O usa el formulario:",
    tzSet: (tz: string) => `Zona horaria de este chat: ${tz}.`,
    tzUnknown: "No conozco esa zona. Prueba una ciudad (/tz phuket) o el nombre de la zona (/tz Asia/Bangkok).",
    newPast: "Eso fue hace más de un día. Para un partido ya jugado, pon la fecha de hoy o de ayer.",
    tooMany: "Son muchos partidos para un día. Inténtalo mañana.",
    resultBtn: "🏁 Resultado",
    didntPlayBtn: "No jugamos",
    toastDidntPlay: "Marcado como cancelado. Nadie tiene que poner el resultado.",
    didntPlayDone: (title: string) => `${title}: marcado como no jugado. Nadie tiene que poner el resultado.`,
    toastNotOrganizer: "Solo el organizador puede hacer eso.",
    whoWon: (title: string) => `${title}: ¿quién ganó?`,
    notYet: "El partido aún no ha empezado.",
    needFour: "El resultado necesita cuatro jugadores en el equipo.",
    needFourPage: "En el chat el resultado necesita cuatro jugadores. La página del partido lo acepta con cualquier número: toca 🏁 Resultado abajo.",
    onlyPlayers: "Solo los jugadores de este partido pueden poner el resultado.",
    onlyOrganizer: "Solo el organizador puede confirmar.",
    resultLocked: "El organizador ya confirmó el resultado.",
    recorded: (winners: string, by: string) => `🏆 ${winners}\nAnotado por ${by}. Organizador: confirma abajo, o toca otra vez para corregir.`,
    confirmBtn: "✔ Confirmar",
    confirmedNote: (winners: string) => `🏆 ${winners} · confirmado ✓`,
    scoreHint: (code: string) => `Los sets, si quieres: /score ${code} 6-3 6-4`,
    scoreHow: "Así: /score CÓDIGO 6-3 6-4 (o responde a la tarjeta con /score 6-3 6-4).",
    scoreNoTeams: "Toca 🏁 Resultado en la tarjeta primero, para que sepa los equipos.",
    noTeamsPage: "Aún no sé las parejas. Toca 🏁 Resultado abajo para anotar el resultado en la página del partido.",
    scoreSaved: (score: string) => `Guardado: ${score}`,
    sameTime: "🔁 ¿A la misma hora la semana que viene?",
    groupMade: (name: string, when: string) => `Hecho: “${name}”. Cada ${when} se publica aquí una tarjeta nueva; los miembros se apuntan o se quitan con un toque.`,
    groupExists: (name: string) => `Este grupo ya existe: “${name}”.`,
    onlyPlayersGroup: "Solo los jugadores de este partido pueden crear el grupo.",
    scoreNudge: (title: string) => `${title}: ¿cómo fue? Responde con el resultado, como 6-4 6-3, o toca 🏁.`,
    scoreAlready: (who: string | null, score: string) => (who ? `${who} ya añadió el resultado: ${score}` : `El resultado ya está: ${score}`),
    scoreBy: (who: string) => `Anotado por ${who}`,
    cardBtn: "📸 Foto y compartir",
    feedbackAdded: "Añadido a tu nota, gracias.",
    toastSaved: "Guardado ✅",
    share: "📤 Compartir",
    privateHelp: "Aquí también puedes:\n/new mañana 19:00 Rawai crea un partido; comparte su tarjeta en cualquier chat con 📤\n/games muestra partidos abiertos cerca de ti (añade una ciudad: /games phuket)\nPega un enlace de kicksma.sh o un código y te muestro la tarjeta.\n/coach: tu agenda de clases, si entrenas (los alumnos reservan solos, los bonos se cuentan solos).",
    coachLink: "Tu asistente: los alumnos reservan las horas libres solos, los bonos se cuentan solos, cada cambio ocurre mientras entrenas. Ábrelo aquí; la configuración lleva un minuto.",
    coachOpen: "Abrir mi asistente",
    coachLinkExpired: "Ese enlace ha caducado. Abre kicksma.sh/coach y toca el botón otra vez.",
    coachLinkOther: "Este asistente ya está vinculado a otra cuenta de Telegram.",
    gamesTitle: (city: string) => `Partidos abiertos · ${city}`,
    gamesMine: "Tus próximos partidos",
    gamesNone: (city: string) => `No hay partidos abiertos en ${city} ahora mismo. Crea uno: /new mañana 19:00 <club>.`,
    gamesWhichCity: "¿Qué ciudad? /games phuket o /games singapore.",
    inlineNothing: "Aún no hay partidos para compartir. Crea uno en un chat conmigo: /new mañana 19:00 <club>.",
    inlineHint: "Crear un partido",
    spotsShort: (n: number, cap: number) => `${n}/${cap}`,
    orgNote: (kind: string, name: string, n: number, cap: number) =>
      kind === "joined" ? `✅ ${name} se apunta · ${n}/${cap}` : kind === "waitlisted" ? `⏳ ${name} entró en la lista de espera` : kind === "left" ? `↩️ ${name} se fue · ${n}/${cap}` : kind === "requested" ? `🙋 ${name} pide unirse (fuera del rango de nivel)` : kind === "confirmed" ? `✅ ${name} confirmó · ${n}/${cap}` : kind === "declined" ? `❌ ${name} declinó` : `⬆️ ${name} entró desde la lista de espera · ${n}/${cap}`,
  },
} as const;

export type BotStrings = (typeof STRINGS)[BotLocale];
export const strings = (locale: BotLocale): BotStrings => STRINGS[locale];

const MAX_LINES = 16;

export function cardTitle(detail: EventDetail, locale: BotLocale): string {
  const ev = detail.event;
  const s = strings(locale);
  const fallback = ev.type === "tournament" ? (ev.format === "mexicano" ? s.formatMexicano : ev.format === "king" ? s.formatKing : s.tournament) : s.match;
  return calendarTitle(ev, fallback);
}

export function whereLine(detail: EventDetail, locale: BotLocale): string {
  const ev = detail.event;
  const s = strings(locale);
  const venue = ev.venueName ?? s.courtTbd;
  return ev.court ? `${venue} · ${s.court(ev.court)}` : venue;
}

export function whenLine(detail: EventDetail, locale: BotLocale): string {
  const ev = detail.event;
  return `${formatEventDay(ev.startsAt, ev.tz, locale)} · ${formatEventTime(ev.startsAt, ev.tz, locale)}`;
}

/** The one message per match the bot keeps edited. HTML parse mode. */
export function renderCard(detail: EventDetail, base: string, locale: BotLocale, now = new Date()): { text: string; keyboard: InlineKeyboard; complete: boolean } {
  const ev = detail.event;
  const s = strings(locale);
  // Inside Telegram the match opens in the Mini App (signed in, no browser) once the owner has created it; the web page otherwise.
  const url = miniAppUrl(ev.code) ?? `${base}/${ev.code}`;
  const seats = detail.roster.filter((x) => x.position <= ev.capacity).sort((a, b) => a.position - b.position);
  const occupied = seats.filter(isOccupied).length;
  const complete = lineupComplete(detail.roster, ev.capacity);
  const cancelled = ev.status === "cancelled";
  const started = now.getTime() >= ev.startsAt.getTime();
  const past = ev.status === "past" || started;
  // After the start a match takes its result from the card; once the organizer confirmed, the button goes.
  const resultOpen = ev.type === "match" && !cancelled && started && !ev.scoreLockedByCreator;
  const lines: string[] = [];
  lines.push(`🎾 <b>${esc(cardTitle(detail, locale))}</b>`);
  lines.push(`📅 ${esc(formatEventDay(ev.startsAt, ev.tz, locale))} · ${esc(formatEventTime(ev.startsAt, ev.tz, locale))}`);
  lines.push(`📍 ${esc(whereLine(detail, locale))}`);
  const range = { min: ev.levelMin, max: ev.levelMax };
  if (hasRange(range)) lines.push(`🎚 ${s.level} ${esc(formatRange(range, { between: (a, b) => `${a}–${b}`, plus: (a) => `${a}+`, upTo: (b) => `≤ ${b}` }))}`);
  if (ev.cost) lines.push(`💸 ${esc(ev.cost)}${ev.payNote ? ` · ${esc(ev.payNote)}` : ""}`);
  lines.push("");
  lines.push(`<b>${s.players} ${occupied}/${ev.capacity}</b>`);
  const shown = seats.slice(0, MAX_LINES);
  for (const seat of shown) {
    if (isOccupied(seat)) {
      const name = seat.player?.displayName ?? seat.invitedName ?? "?";
      const level = seat.player?.level != null ? ` <i>${formatLevel(seat.player.level)}</i>` : "";
      const org = seat.playerId === ev.creatorPlayerId ? ` · ${s.organizer}` : "";
      lines.push(`${seat.position}. ${esc(name)}${level}${org}`);
    } else if (seat.status === "invited") {
      lines.push(`${seat.position}. ${esc(seat.invitedName ?? "?")} <i>(${s.reserved})</i>`);
    } else {
      lines.push(`${seat.position}. —`);
    }
  }
  if (seats.length > shown.length) lines.push(`… +${seats.length - shown.length}`);
  if (detail.waitlist.length > 0) lines.push(s.waitlist(detail.waitlist.length));
  lines.push("");
  const spotsLeft = Math.max(0, ev.capacity - occupied - seats.filter((x) => x.status === "invited").length);
  const status = cancelled ? `❌ <b>${s.cancelled}</b>` : past ? s.past : complete ? `<b>${s.complete}</b>` : spotsLeft > 0 ? `<b>${s.spots(spotsLeft)}</b>` : ev.whenFull === "waitlist" ? s.full : s.closed;
  lines.push(status);
  const keyboard: InlineKeyboard =
    cancelled || past
      ? { inline_keyboard: resultOpen ? [[{ text: s.resultBtn, callback_data: `r:${ev.code}` }], [{ text: s.open, url }]] : [[{ text: s.open, url }]] }
      : {
          inline_keyboard: [
            [
              { text: s.in, callback_data: `j:${ev.code}` },
              { text: s.out, callback_data: `l:${ev.code}` },
            ],
            [
              { text: s.open, url },
              { text: s.share, switch_inline_query: ev.code },
              ...(ev.venueMapUrl ? [{ text: s.map, url: ev.venueMapUrl }] : []),
            ],
          ],
        };
  return { text: lines.join("\n"), keyboard, complete };
}
