/**
 * What the assistant says in Telegram, to coaches and to students. Three languages,
 * short lines, no framework: a phone screen is the whole budget.
 */
export type CoachBotLocale = "en" | "ru" | "es";
export const coachBotLocale = (v: string | null | undefined): CoachBotLocale => (v?.toLowerCase().startsWith("ru") ? "ru" : v?.toLowerCase().startsWith("es") ? "es" : "en");

const S = {
  en: {
    help: "Your book, one line at a time:\n• anna fri 15 — books Anna Friday 15:00\n• cancel anna fri — cancels it\n• block sat, or block fri 15-17 — keeps time free\n• anna +10 90d 6000 — a package of ten, 90 days, 6000\n• today, tomorrow, week — the agenda\n• low — who is almost out of lessons\nUnknown names become new students.",
    booked: (name: string, when: string, pkg: string) => `Booked ${name}, ${when}. ${pkg}`,
    bookedNew: (name: string) => `${name} is a new student, added and accepted.`,
    undo: "Undo",
    undone: "Undone. The lesson is off and the package is back.",
    cancelled: (name: string, when: string) => `Cancelled ${name}, ${when}. Nothing counted.`,
    nothingToCancel: "No booked lesson matches that.",
    whichOne: "Which one?",
    which: (names: string) => `Which ${names}?`,
    blocked: (when: string) => `Blocked ${when}.`,
    blockedWithLessons: (when: string, list: string) => `Blocked ${when}. Lessons in that window stay booked until you cancel them:\n${list}`,
    packageMade: (name: string, size: number, until: string, amount: string) => `Package for ${name}: ${size} lessons${until}${amount}.`,
    paid: "Paid",
    unpaid: "Not paid",
    markedPaid: "Marked paid.",
    markedUnpaid: "Marked not paid.",
    agendaEmpty: (day: string) => `Nothing booked ${day}.`,
    agenda: (day: string, list: string) => `${day}:\n${list}`,
    lowNone: "Nobody is low on lessons.",
    low: (list: string) => `Almost out:\n${list}`,
    pkgLine: (left: number, size: number, days: number | null) => (days === null ? `${left} of ${size} left.` : `${left} of ${size} left · ${days} d.`),
    noPackage: "No package.",
    slotTaken: "That time is taken. Free nearby:",
    slotTakenNone: "That time is taken and nothing is free nearby that day.",
    past: "That time has passed.",
    // to the coach, about students
    studentBooked: (name: string, when: string, pkg: string) => `${name} booked ${when}. ${pkg}`,
    studentCancelled: (name: string, when: string, outcome: string) => `${name} cancelled ${when}. ${outcome}`,
    outcomeRefunded: "Back on the package.",
    outcomeFreePass: "Late; free pass used.",
    outcomeCounted: "Late; counted.",
    outcomeNone: "",
    studentAsked: (name: string) => `${name} asks to become your student.`,
    accept: "Accept",
    accepted: (name: string) => `${name} accepted. They can book now.`,
    // to students
    yourLessons: "Your lessons",
    noLessons: "No lessons booked.",
    withCoach: (coach: string) => `with ${coach}`,
    book: "Book",
    cancel: "Cancel",
    coachBooked: (coach: string, when: string, pkg: string) => `${coach} booked you ${when}. ${pkg}`,
    coachCancelled: (coach: string, when: string) => `${coach} cancelled ${when}. Nothing counted.`,
    youBooked: (coach: string, when: string, pkg: string) => `Booked: ${when} with ${coach}. ${pkg}`,
    youCancelled: (outcome: string) => `Cancelled. ${outcome}`,
    freeTimes: (coach: string, day: string) => `Free with ${coach} ${day}:`,
    noFree: (coach: string, day: string) => `Nothing free with ${coach} ${day}. Try another day.`,
    notStudent: "Ask your coach to accept you first; the link on their page does it.",
    whichCoach: "With which coach?",
    left: (coach: string, line: string) => `With ${coach}: ${line}`,
    lateWarning: (hours: number) => `Less than ${hours} h before: a free pass or a lesson.`,
    youWereAccepted: (coach: string) => `${coach} accepted you. Book a lesson any time: write me a day and a time, or open the link.`,
    open: "Open",
    studentHelp: "Write me a day and a time to book (fri 15), 'cancel fri' to cancel, or 'left' for your package.",
  },
  ru: {
    help: "Ваша книга, одной строкой:\n• анна пт 15 — записать Анну в пятницу на 15:00\n• отмена анна пт — отменить\n• выходной сб или блок пт 15-17 — закрыть время\n• анна +10 90д 6000 — абонемент на десять, 90 дней, 6000\n• сегодня, завтра, неделя — расписание\n• мало — у кого заканчиваются занятия\nНезнакомое имя становится новым учеником.",
    booked: (name: string, when: string, pkg: string) => `Записано: ${name}, ${when}. ${pkg}`,
    bookedNew: (name: string) => `${name} — новый ученик, добавлен и принят.`,
    undo: "Отменить",
    undone: "Отменено. Занятие снято, абонемент возвращён.",
    cancelled: (name: string, when: string) => `Отменено: ${name}, ${when}. Ничего не списано.`,
    nothingToCancel: "Такого записанного занятия нет.",
    whichOne: "Кого именно?",
    which: (names: string) => `Кого: ${names}?`,
    blocked: (when: string) => `Закрыто: ${when}.`,
    blockedWithLessons: (when: string, list: string) => `Закрыто: ${when}. Занятия в этом окне остаются, пока вы их не отмените:\n${list}`,
    packageMade: (name: string, size: number, until: string, amount: string) => `Абонемент для ${name}: ${size} занятий${until}${amount}.`,
    paid: "Оплачен",
    unpaid: "Не оплачен",
    markedPaid: "Отмечено: оплачен.",
    markedUnpaid: "Отмечено: не оплачен.",
    agendaEmpty: (day: string) => `${day}: ничего не записано.`,
    agenda: (day: string, list: string) => `${day}:\n${list}`,
    lowNone: "Ни у кого занятия не заканчиваются.",
    low: (list: string) => `Почти закончились:\n${list}`,
    pkgLine: (left: number, size: number, days: number | null) => (days === null ? `Осталось ${left} из ${size}.` : `Осталось ${left} из ${size} · ${days} дн.`),
    noPackage: "Без абонемента.",
    slotTaken: "Это время занято. Свободно рядом:",
    slotTakenNone: "Это время занято, и рядом в этот день ничего нет.",
    past: "Это время уже прошло.",
    studentBooked: (name: string, when: string, pkg: string) => `${name}: запись ${when}. ${pkg}`,
    studentCancelled: (name: string, when: string, outcome: string) => `${name}: отмена ${when}. ${outcome}`,
    outcomeRefunded: "Возвращено в абонемент.",
    outcomeFreePass: "Поздно; списана бесплатная отмена.",
    outcomeCounted: "Поздно; занятие списано.",
    outcomeNone: "",
    studentAsked: (name: string) => `${name} просится к вам в ученики.`,
    accept: "Принять",
    accepted: (name: string) => `${name}: принят(а). Теперь может записываться.`,
    yourLessons: "Ваши занятия",
    noLessons: "Занятий не записано.",
    withCoach: (coach: string) => `с ${coach}`,
    book: "Записаться",
    cancel: "Отменить",
    coachBooked: (coach: string, when: string, pkg: string) => `${coach} записал(а) вас: ${when}. ${pkg}`,
    coachCancelled: (coach: string, when: string) => `${coach} отменил(а) ${when}. Ничего не списано.`,
    youBooked: (coach: string, when: string, pkg: string) => `Записано: ${when} с ${coach}. ${pkg}`,
    youCancelled: (outcome: string) => `Отменено. ${outcome}`,
    freeTimes: (coach: string, day: string) => `Свободно у ${coach} ${day}:`,
    noFree: (coach: string, day: string) => `У ${coach} ${day} свободного времени нет. Попробуйте другой день.`,
    notStudent: "Сначала тренер должен вас принять; это делается по ссылке на его странице.",
    whichCoach: "С каким тренером?",
    left: (coach: string, line: string) => `У ${coach}: ${line}`,
    lateWarning: (hours: number) => `Меньше ${hours} ч до занятия: спишется бесплатная отмена или занятие.`,
    youWereAccepted: (coach: string) => `${coach} принял(а) вас. Записывайтесь в любое время: напишите мне день и время или откройте ссылку.`,
    open: "Открыть",
    studentHelp: "Напишите день и время, чтобы записаться (пт 15), «отмена пт», чтобы отменить, или «осталось» про абонемент.",
  },
  es: {
    help: "Tu agenda, en una línea:\n• anna vie 15 — reserva a Anna el viernes a las 15:00\n• cancelar anna vie — la cancela\n• bloquear sáb, o bloquear vie 15-17 — deja el tiempo libre\n• anna +10 90d 6000 — un bono de diez, 90 días, 6000\n• hoy, mañana, semana — la agenda\n• bajo — a quién se le acaban las clases\nUn nombre nuevo se convierte en alumno nuevo.",
    booked: (name: string, when: string, pkg: string) => `Reservado: ${name}, ${when}. ${pkg}`,
    bookedNew: (name: string) => `${name} es alumno nuevo, añadido y aceptado.`,
    undo: "Deshacer",
    undone: "Deshecho. La clase queda anulada y el bono vuelve.",
    cancelled: (name: string, when: string) => `Cancelado: ${name}, ${when}. No cuenta.`,
    nothingToCancel: "No hay ninguna clase reservada así.",
    whichOne: "¿Cuál?",
    which: (names: string) => `¿Cuál: ${names}?`,
    blocked: (when: string) => `Bloqueado: ${when}.`,
    blockedWithLessons: (when: string, list: string) => `Bloqueado: ${when}. Las clases en esa franja siguen hasta que las canceles:\n${list}`,
    packageMade: (name: string, size: number, until: string, amount: string) => `Bono para ${name}: ${size} clases${until}${amount}.`,
    paid: "Pagado",
    unpaid: "Sin pagar",
    markedPaid: "Marcado como pagado.",
    markedUnpaid: "Marcado como no pagado.",
    agendaEmpty: (day: string) => `Nada reservado ${day}.`,
    agenda: (day: string, list: string) => `${day}:\n${list}`,
    lowNone: "A nadie se le acaban las clases.",
    low: (list: string) => `Casi sin clases:\n${list}`,
    pkgLine: (left: number, size: number, days: number | null) => (days === null ? `Quedan ${left} de ${size}.` : `Quedan ${left} de ${size} · ${days} d.`),
    noPackage: "Sin bono.",
    slotTaken: "Esa hora está ocupada. Libre cerca:",
    slotTakenNone: "Esa hora está ocupada y no hay nada libre cerca ese día.",
    past: "Esa hora ya pasó.",
    studentBooked: (name: string, when: string, pkg: string) => `${name} reservó ${when}. ${pkg}`,
    studentCancelled: (name: string, when: string, outcome: string) => `${name} canceló ${when}. ${outcome}`,
    outcomeRefunded: "Vuelve al bono.",
    outcomeFreePass: "Tarde; pase gratis usado.",
    outcomeCounted: "Tarde; cuenta.",
    outcomeNone: "",
    studentAsked: (name: string) => `${name} pide ser tu alumno.`,
    accept: "Aceptar",
    accepted: (name: string) => `${name} aceptado. Ya puede reservar.`,
    yourLessons: "Tus clases",
    noLessons: "No hay clases reservadas.",
    withCoach: (coach: string) => `con ${coach}`,
    book: "Reservar",
    cancel: "Cancelar",
    coachBooked: (coach: string, when: string, pkg: string) => `${coach} te reservó ${when}. ${pkg}`,
    coachCancelled: (coach: string, when: string) => `${coach} canceló ${when}. No cuenta.`,
    youBooked: (coach: string, when: string, pkg: string) => `Reservado: ${when} con ${coach}. ${pkg}`,
    youCancelled: (outcome: string) => `Cancelado. ${outcome}`,
    freeTimes: (coach: string, day: string) => `Libre con ${coach} ${day}:`,
    noFree: (coach: string, day: string) => `Nada libre con ${coach} ${day}. Prueba otro día.`,
    notStudent: "Primero tu entrenador tiene que aceptarte; el enlace de su página lo hace.",
    whichCoach: "¿Con qué entrenador?",
    left: (coach: string, line: string) => `Con ${coach}: ${line}`,
    lateWarning: (hours: number) => `Menos de ${hours} h antes: un pase gratis o una clase.`,
    youWereAccepted: (coach: string) => `${coach} te aceptó. Reserva cuando quieras: escríbeme un día y una hora, o abre el enlace.`,
    open: "Abrir",
    studentHelp: "Escríbeme un día y una hora para reservar (vie 15), «cancelar vie» para cancelar, o «quedan» para tu bono.",
  },
} as const;

export type CoachBotStrings = (typeof S)[CoachBotLocale];
export const coachStrings = (locale: CoachBotLocale): CoachBotStrings => S[locale];

/** "Fri 12 Sep 15:00" in the coach's zone and the reader's language. */
export function whenLabel(at: Date, tz: string, locale: string): string {
  const day = new Intl.DateTimeFormat(locale, { weekday: "short", day: "numeric", month: "short", timeZone: tz }).format(at);
  const time = new Intl.DateTimeFormat(locale, { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: tz }).format(at);
  return `${day} ${time}`;
}

export function dayOnlyLabel(dateStr: string, locale: string): string {
  return new Intl.DateTimeFormat(locale, { weekday: "short", day: "numeric", month: "short", timeZone: "UTC" }).format(new Date(`${dateStr}T00:00:00Z`));
}
