/**
 * What the assistant says in Telegram, to coaches and to students. Three languages,
 * short lines, no framework: a phone screen is the whole budget.
 */
export type CoachBotLocale = "en" | "ru" | "es";
export const coachBotLocale = (v: string | null | undefined): CoachBotLocale => (v?.toLowerCase().startsWith("ru") ? "ru" : v?.toLowerCase().startsWith("es") ? "es" : "en");

const S = {
  en: {
    help: "Your book, one line at a time:\n• anna fri 15 — books Anna Friday 15:00\n• cancel anna fri — cancels it\n• move anna fri 15 — moves the lesson she already has\n• block sat, or block fri 15-17 — keeps time free\n• anna +10 90d 6000 — a package of ten, 90 days, 6000\n• today, tomorrow, week — the agenda\n• low — who is almost out of lessons\n• unpaid — who has not paid yet\n• settings — your hours, price and cutoff\nUnknown names become new students.",
    booked: (name: string, when: string, pkg: string) => `Booked ${name}, ${when}. ${pkg}`,
    bookedNew: (name: string) => `${name} is a new student, added and accepted.`,
    undo: "Undo",
    undone: "Undone. The lesson is off and the package is back.",
    cancelled: (name: string, when: string) => `Cancelled ${name}, ${when}. Nothing counted.`,
    nothingToCancel: "No booked lesson matches that.",
    whichOne: "Which one?",
    which: (names: string) => `Which ${names}?`,
    studentLeft: (name: string) => `${name} is no longer on your list — they removed you as their coach. They can come back from your page.`,
    blocked: (when: string) => `Blocked ${when}.`,
    blockedWithLessons: (when: string, list: string) => `Blocked ${when}. Lessons in that window stay booked until you cancel them:\n${list}`,
    packageMade: (name: string, size: number, until: string, amount: string) => `Package for ${name}: ${size} lessons${until}${amount}.`,
    packageTaken: (name: string, size: number, amount: string) => `${name} took a package from your page: ${size} lessons${amount ? `, ${amount}` : ""}. Not paid yet — mark it paid when it lands.`,
    paid: "Paid",
    unpaid: "Not paid",
    markedPaid: "Marked paid.",
    markedUnpaid: "Marked not paid.",
    // setup and settings, as taps and lines
    setupWhere: "Setting up your assistant. Where do you teach?",
    setupLesson: "How long is a lesson?",
    setupHours: "When do you usually teach?",
    setupDone: (link: string) => `Done. Your assistant is running.\nHand this to your students:\n${link}\nSet the rest one line at a time: price 800, club Rawai Padel.`,
    setupAlready: "You already have an assistant here.",
    hoursMornings: "Mornings",
    hoursAfternoons: "Afternoons",
    hoursBoth: "Both",
    minutesLabel: (n: number) => `${n} min`,
    settings: (list: string) => `Your settings:\n${list}\nChange one: price 800, lesson 60, hours mornings, cutoff 12, passes 1, club Rawai Padel, promptpay 0812345678.`,
    labLesson: "Lesson",
    labHours: "Hours",
    labPrice: "Price",
    labCutoff: "Cancel free until",
    labPasses: "Free late cancellations",
    labClubs: "Where you teach",
    labPromptpay: "PromptPay",
    labZone: "Time zone",
    labNotSet: "not set",
    saved: (what: string, value: string) => `${what}: ${value}.`,
    // moving a lesson, and settling up
    moveWhen: "Move it to when? A day and a time: move anna fri 15.",
    moveWhenStudent: "Move it to when? A day and a time: move fri 15.",
    nothingToMove: "No booked lesson matches that.",
    moved: (name: string, from: string, to: string) => `Moved ${name} from ${from} to ${to}.`,
    youMoved: (from: string, to: string) => `Moved from ${from} to ${to}.`,
    moveTaken: "That hour is already taken.",
    moveOutside: "That is outside the hours taught.",
    moveTooLate: (hours: number) => `Less than ${hours} h before the lesson. Cancel it instead.`,
    moveTooSoon: "That is too soon from now.",
    owesNone: "Nobody owes you anything.",
    owes: (list: string) => `Not paid yet:\n${list}`,
    owesLine: (name: string, amount: string, when: string, claimed: boolean) => `${name} · ${amount} · ${when}${claimed ? " · says they paid" : ""}`,
    youOweNone: "Nothing to pay.",
    youOwe: (total: string, list: string) => `You owe ${total}:\n${list}`,
    youOweLine: (amount: string, when: string, claimed: boolean) => `${amount} · ${when}${claimed ? " · you told them" : ""}`,
    iPaid: "I paid",
    claimSent: "Told your coach. They confirm it when it lands.",
    paidConfirmed: (coach: string, when: string) => `${coach} confirmed your payment for ${when}.`,
    agendaEmpty: (day: string) => `Nothing booked ${day}.`,
    agenda: (day: string, list: string) => `${day}:\n${list}`,
    lowNone: "Nobody is low on lessons.",
    low: (list: string) => `Almost out:\n${list}`,
    pkgLine: (left: number, size: number, days: number | null) => (days === null ? `${left} of ${size} left.` : `${left} of ${size} left · ${days} d.`),
    noPackage: "No package.",
    slotTaken: "That time is taken. Free nearby:",
    slotTakenNone: "That time is taken and nothing is free nearby that day.",
    past: "That time has passed.",
    // to the coach, about students
    studentBooked: (name: string, when: string, pkg: string) => `${name} booked ${when}. ${pkg}`,
    studentCancelled: (name: string, when: string, outcome: string) => `${name} cancelled ${when}. ${outcome}`,
    studentMoved: (name: string, from: string, to: string) => `${name} moved ${from} to ${to}.`,
    paidClaimed: (name: string, when: string, amount: string) => `${name} says they paid ${amount} for ${when}. Mark it paid when it lands.`,
    outcomeRefunded: "Back on the package.",
    outcomeFreePass: "Late; free pass used.",
    outcomeCounted: "Late; counted.",
    outcomeNone: "",
    studentAsked: (name: string) => `${name} asks to become your student.`,
    studentJoined: (name: string) => `${name} is on your list now, through your link.`,
    accept: "Accept",
    accepted: (name: string) => `${name} accepted. They can book now.`,
    // to students
    yourLessons: "Your lessons",
    noLessons: "No lessons booked.",
    withCoach: (coach: string) => `with ${coach}`,
    book: "Book",
    cancel: "Cancel",
    coachBooked: (coach: string, when: string, pkg: string) => `${coach} booked you ${when}. ${pkg}`,
    coachMoved: (coach: string, from: string, to: string) => `${coach} moved your lesson from ${from} to ${to}.`,
    coachCancelled: (coach: string, when: string) => `${coach} cancelled ${when}. Nothing counted.`,
    youBooked: (coach: string, when: string, pkg: string) => `Booked: ${when} with ${coach}. ${pkg}`,
    youCancelled: (outcome: string) => `Cancelled. ${outcome}`,
    freeTimes: (coach: string, day: string) => `Free with ${coach} ${day}:`,
    noFree: (coach: string, day: string) => `Nothing free with ${coach} ${day}. Try another day.`,
    notStudent: "Ask your coach to accept you first; the link on their page does it.",
    paused: (coach: string) => `Your bookings with ${coach} are paused. Message ${coach}.`,
    whichCoach: "With which coach?",
    left: (coach: string, line: string) => `With ${coach}: ${line}`,
    lateWarning: (hours: number) => `Less than ${hours} h before: a free pass or a lesson.`,
    youWereAccepted: (coach: string) => `${coach} accepted you. Book a lesson any time: write me a day and a time, or open the link.`,
    open: "Open",
    studentHelp: "Write me a day and a time to book (fri 15), 'cancel fri' to cancel, 'move fri 15' to move one, 'paid' when you have paid, or 'left' for your package.",
    // the menu under the text field
    menuToday: "📅 Today",
    menuTomorrow: "Tomorrow",
    menuWeek: "Week",
    menuLow: "Almost out",
    menuBook: "＋ Book",
    menuLessons: "🎾 My lessons",
    menuLeft: "Package left",
    menuCancel: "✕ Cancel",
    menuCoach: "Your assistant. Tap a button, or write one line: anna fri 15 books, cancel anna fri cancels, block sat keeps the day free.",
    menuStudent: "Your lessons. Tap a button, or write a day and a time: fri 15.",
    menuBookHow: "Name, day and time: anna fri 15. A new name becomes a new student.",
    menuBookHowStudent: "A day and a time: fri 15. Just a day shows the free times.",
    // the bind from the setup's button
    coachLinked: "Linked. I am your assistant here too: write me one line (anna fri 15 books, tomorrow shows the day, low says who is almost out) and I answer your students while you teach.",
    coachOpen: "Open my assistant",
    commandsCoach: [
      { command: "today", description: "Today's lessons" },
      { command: "week", description: "The week" },
      { command: "coach", description: "Open my assistant" },
      { command: "help", description: "What I do" },
    ],
    commandsStudent: [
      { command: "lessons", description: "My lessons and package" },
      { command: "help", description: "What I do" },
    ],
    menuPlaceholder: "anna fri 15",
    menuPlaceholderStudent: "fri 15",
    // chains: offers, requests, reminders
    altTimes: "Free instead:",
    offer: (coach: string, when: string, minutes: number) => `A spot opened with ${coach}: ${when}. Yours for ${minutes} minutes.`,
    offerTake: "Book it",
    offerNo: "No thanks",
    offerTaken: (when: string, pkg: string) => `Booked ${when}. ${pkg}`,
    offerGone: "That spot is gone.",
    offerLapsed: (when: string) => `The ${when} offer lapsed; it went to the next in line. Join the list again any time.`,
    offerWithdrawn: "Off the list.",
    waitlisted: (when: string) => `On the list for ${when}. The first free spot is yours for 30 minutes.`,
    waitlistedWeek: (week: string) => `On the list for the week of ${week}. The first free spot is yours for 30 minutes.`,
    requestSent: (coach: string, when: string) => `Asked ${coach} for ${when}, outside the usual hours. The answer comes here.`,
    requestAsk: (name: string, when: string) => `${name} asks for ${when}, outside your hours.`,
    requestYes: "Yes",
    requestNo: "No",
    requestAccepted: (coach: string, when: string, pkg: string) => `${coach} said yes: ${when}. ${pkg}`,
    requestDeclined: (coach: string, when: string) => `${coach} can't do ${when}. Pick another time.`,
    requestAnswered: (name: string, yes: boolean) => (yes ? `Booked ${name}.` : `Told ${name} no.`),
    requestGone: "Already answered.",
    reminder: (coach: string, when: string, pkg: string) => `Tomorrow: ${when} with ${coach}. ${pkg}`,
    lowPackage: (coach: string, line: string) => `With ${coach}: ${line} Time for the next package?`,
    managerJoined: (name: string) => `${name} now runs your book with you.`,
    waiting: (n: number) => `${n} waiting for a spot.`,
    // taps: every step of the book as a button; typing only where a name or a figure is unavoidable
    tapWho: "Who is the lesson for?",
    tapNewStudent: "＋ New student",
    tapAskName: "Their name?",
    tapWhichDay: (name: string) => `${name} — which day?`,
    tapWhichDayStudent: (coach: string) => `A lesson with ${coach} — which day?`,
    tapHowLong: "How long?",
    tapWhichTime: (day: string) => `${day} — what time?`,
    tapOtherTime: "✎ Another time",
    tapAskTime: (day: string) => `${day} — what time? Write it like 15:30.`,
    tapBadTime: "That is not a time I can read. Write it like 15:30.",
    tapHowMany: "How many are coming?",
    tapNoFree: (day: string) => `Nothing free ${day}.`,
    tapWaitWeek: "🔔 Tell me when a spot frees up that week",
    tapAskAnother: "❓ Ask for another time",
    tapAskAnotherTime: (day: string) => `${day} — what time would you like? Write it like 19:30. Your coach says yes or no.`,
    tapBack: "‹ Back",
    tapKeep: "Keep it",
    tapCancelAsk: (name: string, when: string) => `Cancel ${name}, ${when}?`,
    tapCancelYes: "✕ Yes, cancel",
    tapWhichLesson: "Which lesson?",
    tapMoveWhere: (name: string, when: string) => `${name}, ${when} — move it to which day?`,
    tapNothingAhead: "Nothing booked in the next two weeks.",
    tapLesson: (name: string, when: string, pkg: string, money: string) => `${name} · ${when}
${pkg}${money ? `
${money}` : ""}`,
    tapMove: "↔ Move",
    tapCancelBtn: "✕ Cancel",
    tapNoShow: "👻 No-show",
    tapCame: "↩ They came after all",
    tapNoShowDone: (name: string, when: string) => `No-show: ${name}, ${when}. The lesson counts.`,
    tapCameDone: (name: string, when: string) => `${name}, ${when}: done after all.`,
    tapOnMe: "🎁 On me",
    tapOnMeDone: (name: string, when: string) => `${name}, ${when}: on you. Nothing owed.`,
    tapMoneyNotPaid: (amount: string) => `${amount} · not paid`,
    tapMoneySaysPaid: (amount: string) => `${amount} · says they paid`,
    tapMoneyPaid: (amount: string) => `${amount} · paid`,
    tapStudents: "Your students",
    tapStudentsNone: "No students yet. Hand out your link; whoever opens it is on the list.",
    tapStudentLine: (name: string, pkg: string, owes: string) => `${name} · ${pkg}${owes ? ` · ${owes}` : ""}`,
    tapOwes: (amount: string) => `owes ${amount}`,
    tapStudentCard: (name: string, pkg: string, owes: string, next: string) => `${name}
${pkg}${owes ? `
${owes}` : ""}
${next}`,
    tapNextLesson: (when: string) => `Next: ${when}`,
    tapNoNext: "Nothing booked.",
    tapBookFor: "＋ Book",
    tapPackageFor: "＋ Package",
    tapWhichPackage: (name: string) => `Which package for ${name}?`,
    tapPackageLabel: (size: number, minutes: number, heads: number, price: string) => `${size} × ${minutes} min${heads > 1 ? ` · ${heads}` : ""} · ${price}`,
    tapPackageCustom: "✎ Another package",
    tapAskPackage: (name: string) => `A package for ${name}: lessons, days and price, like 10 90d 6000.`,
    tapBadPackage: "Write the lessons first, like 10 90d 6000.",
    tapMoney: "Money",
    tapMoneyNone: "Nobody owes you anything.",
    tapMoneyPackage: (name: string, size: number, amount: string) => `${name} · package of ${size} · ${amount}`,
    tapSettingsHow: "Tap to change. Your clubs are the one thing you write: club Rawai Padel.",
    tapSettingsWeb: "Prices, packages and the rest ↗",
    tapStudentWhichCoach: "With which coach?",
    tapPay: "Pay & package",
    tapTakePackage: "Take a package",
    tapPackages: (coach: string) => `Packages with ${coach}:`,
    tapPackagesNone: (coach: string) => `${coach} sells no packages on the page.`,
    tapPackageTaken: (size: number, amount: string, coach: string) => `Your package has started: ${size} lessons. Pay ${amount} to ${coach}.`,
    tapPayHow: (lines: string) => `How to pay:
${lines}`,
    tapPayAtClub: "At the club, cash or card.",
    tapPayPromptpay: "PromptPay: scan the QR above.",
    tapPayLink: "Pay by link",
    tapPayAsk: (coach: string) => `Ask ${coach} how they take payment.`,
    tapHasPackage: "You already have a package with lessons left.",
    tapAskedCoach: (coach: string, when: string) => `Asked ${coach} for ${when}. The answer comes here.`,
    tapEach: (amount: string) => `${amount} each`,
    menuCancelCoach: "✕ Cancel",
    menuMove: "↔ Move",
    menuStudents: "👥 Students",
    menuMoney: "💰 Money",
    menuSettings: "⚙️ Settings",
    menuPay: "💳 Pay & package",
    // numbers and times as taps: a keypad in the chat, hours and minutes as buttons
    tapKeypadOk: "✓ Done",
    tapEnter: (label: string, digits: string) => `${label}: ${digits || "…"}`,
    tapPairEach: "Pair, each",
    tapSecondLength: "Second length",
    tapSecondOne: "Second length, one person",
    tapSecondPair: "Second length, pair each",
    tapFee: "Extra outside your hours",
    tapNone: "None",
    tapOffersTitle: "Packages on your page",
    tapOffersNone: "No packages on your page yet. Students pick one there with a tap.",
    tapOfferAdd: "＋ Add a package",
    tapHowManyLessons: "How many lessons?",
    tapValidFor: "Valid for how long?",
    tapNoExpiry: "No expiry",
    tapForHowMany: "For how many on court?",
    tapPriceEach: (hint: string) => `Price, each${hint ? ` (${hint})` : ""}`,
    tapWhichHour: "Which hour?",
    tapWhichMinute: (hour: string) => `${hour} — and the minutes?`,
    tapDays: (n: number) => `${n} d`,
    menuBlock: "🚫 Block time",
    tapBlockDay: "Block which day?",
    tapBlockWhat: (day: string) => `${day} — block what?`,
    tapAllDay: "All day",
    menuCoachTaps: "Your assistant. Tap a button: book, cancel, move, block, students, money, settings. Everything is a tap; a name or a price is the only thing you ever write.",
    menuStudentTaps: "Your lessons. Tap a button: book, move, cancel, pay. A time is the only thing you ever write.",
  },
  ru: {
    help: "Ваша книга, одной строкой:\n• анна пт 15 — записать Анну в пятницу на 15:00\n• отмена анна пт — отменить\n• перенеси анна пт 15 — перенести её занятие\n• выходной сб или блок пт 15-17 — закрыть время\n• анна +10 90д 6000 — абонемент на десять, 90 дней, 6000\n• сегодня, завтра, неделя — расписание\n• мало — у кого заканчиваются занятия\n• долги — кто ещё не оплатил\n• настройки — часы, цена и порог отмены\nНезнакомое имя становится новым учеником.",
    booked: (name: string, when: string, pkg: string) => `Записано: ${name}, ${when}. ${pkg}`,
    bookedNew: (name: string) => `${name} — новый ученик, добавлен и принят.`,
    undo: "Отменить",
    undone: "Отменено. Занятие снято, абонемент возвращён.",
    cancelled: (name: string, when: string) => `Отменено: ${name}, ${when}. Ничего не списано.`,
    nothingToCancel: "Такого записанного занятия нет.",
    whichOne: "Кого именно?",
    which: (names: string) => `Кого: ${names}?`,
    studentLeft: (name: string) => `${name} больше не в вашем списке — этот ученик удалил вас как тренера. Вернуться можно с вашей страницы.`,
    blocked: (when: string) => `Закрыто: ${when}.`,
    blockedWithLessons: (when: string, list: string) => `Закрыто: ${when}. Занятия в этом окне остаются, пока вы их не отмените:\n${list}`,
    packageMade: (name: string, size: number, until: string, amount: string) => `Абонемент для ${name}: ${size} занятий${until}${amount}.`,
    packageTaken: (name: string, size: number, amount: string) => `${name} взял(а) абонемент с вашей страницы: ${size} занятий${amount ? `, ${amount}` : ""}. Ещё не оплачен — отметьте оплату, когда деньги придут.`,
    paid: "Оплачен",
    unpaid: "Не оплачен",
    markedPaid: "Отмечено: оплачен.",
    markedUnpaid: "Отмечено: не оплачен.",
    // настройка и параметры — кнопками и строками
    setupWhere: "Настраиваю вашего ассистента. Где вы тренируете?",
    setupLesson: "Сколько длится занятие?",
    setupHours: "Когда вы обычно тренируете?",
    setupDone: (link: string) => `Готово. Ассистент работает.\nДайте эту ссылку ученикам:\n${link}\nОстальное — по одной строке: цена 800, клуб Rawai Padel.`,
    setupAlready: "Ассистент у вас уже есть.",
    hoursMornings: "Утро",
    hoursAfternoons: "Вечер",
    hoursBoth: "И то, и другое",
    minutesLabel: (n: number) => `${n} мин`,
    settings: (list: string) => `Ваши настройки:\n${list}\nИзменить: цена 800, занятие 60, часы утро, порог 12, пропуски 1, клуб Rawai Padel, promptpay 0812345678.`,
    labLesson: "Занятие",
    labHours: "Часы",
    labPrice: "Цена",
    labCutoff: "Бесплатная отмена до",
    labPasses: "Бесплатных поздних отмен",
    labClubs: "Где вы тренируете",
    labPromptpay: "PromptPay",
    labZone: "Часовой пояс",
    labNotSet: "не задано",
    saved: (what: string, value: string) => `${what}: ${value}.`,
    // перенос занятия и оплата
    moveWhen: "Перенести на когда? День и время: перенеси анна пт 15.",
    moveWhenStudent: "Перенести на когда? День и время: перенеси пт 15.",
    nothingToMove: "Такого записанного занятия нет.",
    moved: (name: string, from: string, to: string) => `Перенесено: ${name}, с ${from} на ${to}.`,
    youMoved: (from: string, to: string) => `Перенесено: с ${from} на ${to}.`,
    moveTaken: "Это время уже занято.",
    moveOutside: "Это время вне рабочих часов.",
    moveTooLate: (hours: number) => `Меньше ${hours} ч до занятия. Отмените его вместо переноса.`,
    moveTooSoon: "Слишком скоро.",
    owesNone: "Никто вам не должен.",
    owes: (list: string) => `Ещё не оплачено:\n${list}`,
    owesLine: (name: string, amount: string, when: string, claimed: boolean) => `${name} · ${amount} · ${when}${claimed ? " · говорит, что оплатил" : ""}`,
    youOweNone: "Оплачивать нечего.",
    youOwe: (total: string, list: string) => `К оплате ${total}:\n${list}`,
    youOweLine: (amount: string, when: string, claimed: boolean) => `${amount} · ${when}${claimed ? " · вы сообщили" : ""}`,
    iPaid: "Я оплатил",
    claimSent: "Сообщил тренеру. Он подтвердит, когда деньги придут.",
    paidConfirmed: (coach: string, when: string) => `${coach} подтвердил оплату за ${when}.`,
    agendaEmpty: (day: string) => `${day}: ничего не записано.`,
    agenda: (day: string, list: string) => `${day}:\n${list}`,
    lowNone: "Ни у кого занятия не заканчиваются.",
    low: (list: string) => `Почти закончились:\n${list}`,
    pkgLine: (left: number, size: number, days: number | null) => (days === null ? `Осталось ${left} из ${size}.` : `Осталось ${left} из ${size} · ${days} дн.`),
    noPackage: "Без абонемента.",
    slotTaken: "Это время занято. Свободно рядом:",
    slotTakenNone: "Это время занято, и рядом в этот день ничего нет.",
    past: "Это время уже прошло.",
    studentBooked: (name: string, when: string, pkg: string) => `${name}: запись ${when}. ${pkg}`,
    studentCancelled: (name: string, when: string, outcome: string) => `${name}: отмена ${when}. ${outcome}`,
    studentMoved: (name: string, from: string, to: string) => `${name}: перенос с ${from} на ${to}.`,
    paidClaimed: (name: string, when: string, amount: string) => `${name}: оплата ${amount} за ${when} отправлена. Отметьте, когда придёт.`,
    outcomeRefunded: "Возвращено в абонемент.",
    outcomeFreePass: "Поздно; списана бесплатная отмена.",
    outcomeCounted: "Поздно; занятие списано.",
    outcomeNone: "",
    studentAsked: (name: string) => `${name} просится к вам в ученики.`,
    studentJoined: (name: string) => `${name} теперь в вашем списке — по вашей ссылке.`,
    accept: "Принять",
    accepted: (name: string) => `${name}: принят(а). Теперь может записываться.`,
    yourLessons: "Ваши занятия",
    noLessons: "Занятий не записано.",
    withCoach: (coach: string) => `с ${coach}`,
    book: "Записаться",
    cancel: "Отменить",
    coachBooked: (coach: string, when: string, pkg: string) => `${coach} записал(а) вас: ${when}. ${pkg}`,
    coachMoved: (coach: string, from: string, to: string) => `${coach} перенёс(ла) занятие с ${from} на ${to}.`,
    coachCancelled: (coach: string, when: string) => `${coach} отменил(а) ${when}. Ничего не списано.`,
    youBooked: (coach: string, when: string, pkg: string) => `Записано: ${when} с ${coach}. ${pkg}`,
    youCancelled: (outcome: string) => `Отменено. ${outcome}`,
    freeTimes: (coach: string, day: string) => `Свободно у ${coach} ${day}:`,
    noFree: (coach: string, day: string) => `У ${coach} ${day} свободного времени нет. Попробуйте другой день.`,
    notStudent: "Сначала тренер должен вас принять; это делается по ссылке на его странице.",
    paused: (coach: string) => `Запись у ${coach} приостановлена. Напишите ${coach}.`,
    whichCoach: "С каким тренером?",
    left: (coach: string, line: string) => `У ${coach}: ${line}`,
    lateWarning: (hours: number) => `Меньше ${hours} ч до занятия: спишется бесплатная отмена или занятие.`,
    youWereAccepted: (coach: string) => `${coach} принял(а) вас. Записывайтесь в любое время: напишите мне день и время или откройте ссылку.`,
    open: "Открыть",
    studentHelp: "Напишите день и время, чтобы записаться (пт 15), «отмена пт», чтобы отменить, «перенеси пт 15», чтобы перенести, «оплатил», когда оплатили, или «осталось» про абонемент.",
    // меню под полем ввода
    menuToday: "📅 Сегодня",
    menuTomorrow: "Завтра",
    menuWeek: "Неделя",
    menuLow: "Мало занятий",
    menuBook: "＋ Записать",
    menuLessons: "🎾 Мои занятия",
    menuLeft: "Остаток",
    menuCancel: "✕ Отменить",
    menuCoach: "Ваш ассистент. Нажмите кнопку или напишите строку: анна пт 15 — запись, отмена анна пт — отмена, выходной сб — день закрыт.",
    menuStudent: "Ваши занятия. Нажмите кнопку или напишите день и время: пт 15.",
    menuBookHow: "Имя, день и время: анна пт 15. Новое имя становится новым учеником.",
    menuBookHowStudent: "День и время: пт 15. Только день — покажу свободное время.",
    // привязка по кнопке из настройки
    coachLinked: "Связано. Здесь я тоже ваш ассистент: напишите одну строку (анна пт 15 — запись, завтра — день, мало — кто на исходе), а ученикам я отвечаю, пока вы тренируете.",
    coachOpen: "Открыть ассистента",
    commandsCoach: [
      { command: "today", description: "Занятия сегодня" },
      { command: "week", description: "Неделя" },
      { command: "coach", description: "Открыть ассистента" },
      { command: "help", description: "Что я умею" },
    ],
    commandsStudent: [
      { command: "lessons", description: "Мои занятия и абонемент" },
      { command: "help", description: "Что я умею" },
    ],
    menuPlaceholder: "анна пт 15",
    menuPlaceholderStudent: "пт 15",
    // chains: offers, requests, reminders
    altTimes: "Свободно вместо этого:",
    offer: (coach: string, when: string, minutes: number) => `Освободилось место у ${coach}: ${when}. Ваше на ${minutes} минут.`,
    offerTake: "Забронировать",
    offerNo: "Не нужно",
    offerTaken: (when: string, pkg: string) => `Записано: ${when}. ${pkg}`,
    offerGone: "Это место уже занято.",
    offerLapsed: (when: string) => `Предложение на ${when} истекло и ушло следующему в очереди. Встать в очередь можно снова в любой момент.`,
    offerWithdrawn: "Вы вышли из очереди.",
    waitlisted: (when: string) => `Вы в очереди на ${when}. Первое свободное место — ваше на 30 минут.`,
    waitlistedWeek: (week: string) => `Вы в очереди на неделю с ${week}. Первое свободное место — ваше на 30 минут.`,
    requestSent: (coach: string, when: string) => `Запрос к ${coach} на ${when}, вне обычных часов. Ответ придёт сюда.`,
    requestAsk: (name: string, when: string) => `${name} просит ${when}, вне ваших часов.`,
    requestYes: "Да",
    requestNo: "Нет",
    requestAccepted: (coach: string, when: string, pkg: string) => `${coach} согласился(ась): ${when}. ${pkg}`,
    requestDeclined: (coach: string, when: string) => `${coach} не может ${when}. Выберите другое время.`,
    requestAnswered: (name: string, yes: boolean) => (yes ? `Записано: ${name}.` : `${name} получит отказ.`),
    requestGone: "Уже отвечено.",
    reminder: (coach: string, when: string, pkg: string) => `Завтра: ${when} у ${coach}. ${pkg}`,
    lowPackage: (coach: string, line: string) => `У ${coach}: ${line} Пора продлить пакет?`,
    managerJoined: (name: string) => `${name} теперь ведёт вашу запись вместе с вами.`,
    waiting: (n: number) => `В очереди: ${n}.`,
    // кнопки: каждый шаг книги — кнопка; ввод только там, где без имени или цифры не обойтись
    tapWho: "Для кого занятие?",
    tapNewStudent: "＋ Новый ученик",
    tapAskName: "Как его зовут?",
    tapWhichDay: (name: string) => `${name} — какой день?`,
    tapWhichDayStudent: (coach: string) => `Занятие с ${coach} — какой день?`,
    tapHowLong: "Сколько длится?",
    tapWhichTime: (day: string) => `${day} — во сколько?`,
    tapOtherTime: "✎ Другое время",
    tapAskTime: (day: string) => `${day} — во сколько? Напишите так: 15:30.`,
    tapBadTime: "Не могу прочитать время. Напишите так: 15:30.",
    tapHowMany: "Сколько человек придёт?",
    tapNoFree: (day: string) => `${day}: свободного времени нет.`,
    tapWaitWeek: "🔔 Сообщить, когда освободится место на той неделе",
    tapAskAnother: "❓ Попросить другое время",
    tapAskAnotherTime: (day: string) => `${day} — во сколько хотите? Напишите так: 19:30. Тренер ответит да или нет.`,
    tapBack: "‹ Назад",
    tapKeep: "Оставить",
    tapCancelAsk: (name: string, when: string) => `Отменить ${name}, ${when}?`,
    tapCancelYes: "✕ Да, отменить",
    tapWhichLesson: "Какое занятие?",
    tapMoveWhere: (name: string, when: string) => `${name}, ${when} — на какой день перенести?`,
    tapNothingAhead: "В ближайшие две недели ничего не записано.",
    tapLesson: (name: string, when: string, pkg: string, money: string) => `${name} · ${when}
${pkg}${money ? `
${money}` : ""}`,
    tapMove: "↔ Перенести",
    tapCancelBtn: "✕ Отменить",
    tapNoShow: "👻 Не пришёл",
    tapCame: "↩ Всё-таки пришёл",
    tapNoShowDone: (name: string, when: string) => `Не пришёл: ${name}, ${when}. Занятие засчитано.`,
    tapCameDone: (name: string, when: string) => `${name}, ${when}: всё-таки было.`,
    tapOnMe: "🎁 За мой счёт",
    tapOnMeDone: (name: string, when: string) => `${name}, ${when}: за ваш счёт. Ничего не должен.`,
    tapMoneyNotPaid: (amount: string) => `${amount} · не оплачено`,
    tapMoneySaysPaid: (amount: string) => `${amount} · говорит, что оплатил`,
    tapMoneyPaid: (amount: string) => `${amount} · оплачено`,
    tapStudents: "Ваши ученики",
    tapStudentsNone: "Учеников пока нет. Дайте ссылку: кто откроет — в списке.",
    tapStudentLine: (name: string, pkg: string, owes: string) => `${name} · ${pkg}${owes ? ` · ${owes}` : ""}`,
    tapOwes: (amount: string) => `должен ${amount}`,
    tapStudentCard: (name: string, pkg: string, owes: string, next: string) => `${name}
${pkg}${owes ? `
${owes}` : ""}
${next}`,
    tapNextLesson: (when: string) => `Следующее: ${when}`,
    tapNoNext: "Ничего не записано.",
    tapBookFor: "＋ Записать",
    tapPackageFor: "＋ Абонемент",
    tapWhichPackage: (name: string) => `Какой абонемент для ${name}?`,
    tapPackageLabel: (size: number, minutes: number, heads: number, price: string) => `${size} × ${minutes} мин${heads > 1 ? ` · ${heads}` : ""} · ${price}`,
    tapPackageCustom: "✎ Другой абонемент",
    tapAskPackage: (name: string) => `Абонемент для ${name}: занятия, дни и цена, например 10 90д 6000.`,
    tapBadPackage: "Сначала число занятий, например 10 90д 6000.",
    tapMoney: "Деньги",
    tapMoneyNone: "Никто вам не должен.",
    tapMoneyPackage: (name: string, size: number, amount: string) => `${name} · абонемент на ${size} · ${amount}`,
    tapSettingsHow: "Нажмите, чтобы изменить. Клубы — единственное, что пишут: клуб Rawai Padel.",
    tapSettingsWeb: "Цены, абонементы и остальное ↗",
    tapStudentWhichCoach: "С каким тренером?",
    tapPay: "Оплата и абонемент",
    tapTakePackage: "Взять абонемент",
    tapPackages: (coach: string) => `Абонементы у ${coach}:`,
    tapPackagesNone: (coach: string) => `${coach} не продаёт абонементы на странице.`,
    tapPackageTaken: (size: number, amount: string, coach: string) => `Абонемент начался: ${size} занятий. Оплатите ${amount} — ${coach}.`,
    tapPayHow: (lines: string) => `Как оплатить:
${lines}`,
    tapPayAtClub: "В клубе, наличными или картой.",
    tapPayPromptpay: "PromptPay: отсканируйте QR выше.",
    tapPayLink: "Оплатить по ссылке",
    tapPayAsk: (coach: string) => `Спросите ${coach}, как удобнее оплатить.`,
    tapHasPackage: "У вас уже есть абонемент с оставшимися занятиями.",
    tapAskedCoach: (coach: string, when: string) => `Попросили ${coach} на ${when}. Ответ придёт сюда.`,
    tapEach: (amount: string) => `${amount} с каждого`,
    menuCancelCoach: "✕ Отменить",
    menuMove: "↔ Перенести",
    menuStudents: "👥 Ученики",
    menuMoney: "💰 Деньги",
    menuSettings: "⚙️ Настройки",
    menuPay: "💳 Оплата и абонемент",
    // цифры и время — кнопками: клавиатура в чате, часы и минуты как кнопки
    tapKeypadOk: "✓ Готово",
    tapEnter: (label: string, digits: string) => `${label}: ${digits || "…"}`,
    tapPairEach: "Пара, с каждого",
    tapSecondLength: "Вторая длина",
    tapSecondOne: "Вторая длина, один человек",
    tapSecondPair: "Вторая длина, пара с каждого",
    tapFee: "Доплата вне ваших часов",
    tapNone: "Нет",
    tapOffersTitle: "Абонементы на вашей странице",
    tapOffersNone: "Абонементов на странице пока нет. Ученики выбирают их там одним нажатием.",
    tapOfferAdd: "＋ Добавить абонемент",
    tapHowManyLessons: "Сколько занятий?",
    tapValidFor: "На какой срок?",
    tapNoExpiry: "Без срока",
    tapForHowMany: "На скольких человек?",
    tapPriceEach: (hint: string) => `Цена, с каждого${hint ? ` (${hint})` : ""}`,
    tapWhichHour: "Который час?",
    tapWhichMinute: (hour: string) => `${hour} — а минуты?`,
    tapDays: (n: number) => `${n} дн.`,
    menuBlock: "🚫 Закрыть время",
    tapBlockDay: "Какой день закрыть?",
    tapBlockWhat: (day: string) => `${day} — что закрыть?`,
    tapAllDay: "Весь день",
    menuCoachTaps: "Ваш ассистент. Нажимайте кнопки: записать, отменить, перенести, закрыть время, ученики, деньги, настройки. Всё кнопками; писать нужно только имя или цену.",
    menuStudentTaps: "Ваши занятия. Нажимайте кнопки: записаться, перенести, отменить, оплатить. Писать нужно только время.",
  },
  es: {
    help: "Tu agenda, en una línea:\n• anna vie 15 — reserva a Anna el viernes a las 15:00\n• cancelar anna vie — la cancela\n• mover anna vie 15 — mueve la clase que ya tiene\n• bloquear sáb, o bloquear vie 15-17 — deja el tiempo libre\n• anna +10 90d 6000 — un bono de diez, 90 días, 6000\n• hoy, mañana, semana — la agenda\n• bajo — a quién se le acaban las clases\n• deudas — quién no ha pagado\n• ajustes — tus horas, precio y margen\nUn nombre nuevo se convierte en alumno nuevo.",
    booked: (name: string, when: string, pkg: string) => `Reservado: ${name}, ${when}. ${pkg}`,
    bookedNew: (name: string) => `${name} es alumno nuevo, añadido y aceptado.`,
    undo: "Deshacer",
    undone: "Deshecho. La clase queda anulada y el bono vuelve.",
    cancelled: (name: string, when: string) => `Cancelado: ${name}, ${when}. No cuenta.`,
    nothingToCancel: "No hay ninguna clase reservada así.",
    whichOne: "¿Cuál?",
    which: (names: string) => `¿Cuál: ${names}?`,
    studentLeft: (name: string) => `${name} ya no está en tu lista: te quitó como entrenador. Puede volver desde tu página.`,
    blocked: (when: string) => `Bloqueado: ${when}.`,
    blockedWithLessons: (when: string, list: string) => `Bloqueado: ${when}. Las clases en esa franja siguen hasta que las canceles:\n${list}`,
    packageMade: (name: string, size: number, until: string, amount: string) => `Bono para ${name}: ${size} clases${until}${amount}.`,
    packageTaken: (name: string, size: number, amount: string) => `${name} ha cogido un bono desde tu página: ${size} clases${amount ? `, ${amount}` : ""}. Aún sin pagar: márcalo pagado cuando llegue.`,
    paid: "Pagado",
    unpaid: "Sin pagar",
    markedPaid: "Marcado como pagado.",
    markedUnpaid: "Marcado como no pagado.",
    // configuración y ajustes, con toques y líneas
    setupWhere: "Configurando tu asistente. ¿Dónde das clases?",
    setupLesson: "¿Cuánto dura una clase?",
    setupHours: "¿Cuándo sueles dar clase?",
    setupDone: (link: string) => `Listo. Tu asistente ya funciona.\nDale este enlace a tus alumnos:\n${link}\nEl resto, línea a línea: precio 800, club Rawai Padel.`,
    setupAlready: "Ya tienes un asistente aquí.",
    hoursMornings: "Mañanas",
    hoursAfternoons: "Tardes",
    hoursBoth: "Ambos",
    minutesLabel: (n: number) => `${n} min`,
    settings: (list: string) => `Tus ajustes:\n${list}\nCambia uno: precio 800, clase 60, horas mañanas, margen 12, pases 1, club Rawai Padel, promptpay 0812345678.`,
    labLesson: "Clase",
    labHours: "Horas",
    labPrice: "Precio",
    labCutoff: "Cancelación gratis hasta",
    labPasses: "Cancelaciones tardías gratis",
    labClubs: "Dónde das clases",
    labPromptpay: "PromptPay",
    labZone: "Zona horaria",
    labNotSet: "sin definir",
    saved: (what: string, value: string) => `${what}: ${value}.`,
    // mover una clase y pagarla
    moveWhen: "¿Moverla a cuándo? Un día y una hora: mover anna vie 15.",
    moveWhenStudent: "¿Moverla a cuándo? Un día y una hora: mover vie 15.",
    nothingToMove: "No hay ninguna clase reservada así.",
    moved: (name: string, from: string, to: string) => `Movida ${name}, de ${from} a ${to}.`,
    youMoved: (from: string, to: string) => `Movida de ${from} a ${to}.`,
    moveTaken: "Esa hora ya está ocupada.",
    moveOutside: "Eso queda fuera de las horas de clase.",
    moveTooLate: (hours: number) => `Menos de ${hours} h antes de la clase. Cancélala en su lugar.`,
    moveTooSoon: "Eso es demasiado pronto.",
    owesNone: "Nadie te debe nada.",
    owes: (list: string) => `Sin pagar todavía:\n${list}`,
    owesLine: (name: string, amount: string, when: string, claimed: boolean) => `${name} · ${amount} · ${when}${claimed ? " · dice que pagó" : ""}`,
    youOweNone: "No hay nada que pagar.",
    youOwe: (total: string, list: string) => `Debes ${total}:\n${list}`,
    youOweLine: (amount: string, when: string, claimed: boolean) => `${amount} · ${when}${claimed ? " · se lo dijiste" : ""}`,
    iPaid: "He pagado",
    claimSent: "Se lo he dicho a tu entrenador. Lo confirmará cuando llegue.",
    paidConfirmed: (coach: string, when: string) => `${coach} confirmó tu pago de ${when}.`,
    agendaEmpty: (day: string) => `Nada reservado ${day}.`,
    agenda: (day: string, list: string) => `${day}:\n${list}`,
    lowNone: "A nadie se le acaban las clases.",
    low: (list: string) => `Casi sin clases:\n${list}`,
    pkgLine: (left: number, size: number, days: number | null) => (days === null ? `Quedan ${left} de ${size}.` : `Quedan ${left} de ${size} · ${days} d.`),
    noPackage: "Sin bono.",
    slotTaken: "Esa hora está ocupada. Libre cerca:",
    slotTakenNone: "Esa hora está ocupada y no hay nada libre cerca ese día.",
    past: "Esa hora ya pasó.",
    studentBooked: (name: string, when: string, pkg: string) => `${name} reservó ${when}. ${pkg}`,
    studentCancelled: (name: string, when: string, outcome: string) => `${name} canceló ${when}. ${outcome}`,
    studentMoved: (name: string, from: string, to: string) => `${name} cambió ${from} a ${to}.`,
    paidClaimed: (name: string, when: string, amount: string) => `${name} dice que pagó ${amount} por ${when}. Márcalo cuando llegue.`,
    outcomeRefunded: "Vuelve al bono.",
    outcomeFreePass: "Tarde; pase gratis usado.",
    outcomeCounted: "Tarde; cuenta.",
    outcomeNone: "",
    studentAsked: (name: string) => `${name} pide ser tu alumno.`,
    studentJoined: (name: string) => `${name} ya está en tu lista, por tu enlace.`,
    accept: "Aceptar",
    accepted: (name: string) => `${name} aceptado. Ya puede reservar.`,
    yourLessons: "Tus clases",
    noLessons: "No hay clases reservadas.",
    withCoach: (coach: string) => `con ${coach}`,
    book: "Reservar",
    cancel: "Cancelar",
    coachBooked: (coach: string, when: string, pkg: string) => `${coach} te reservó ${when}. ${pkg}`,
    coachMoved: (coach: string, from: string, to: string) => `${coach} cambió tu clase de ${from} a ${to}.`,
    coachCancelled: (coach: string, when: string) => `${coach} canceló ${when}. No cuenta.`,
    youBooked: (coach: string, when: string, pkg: string) => `Reservado: ${when} con ${coach}. ${pkg}`,
    youCancelled: (outcome: string) => `Cancelado. ${outcome}`,
    freeTimes: (coach: string, day: string) => `Libre con ${coach} ${day}:`,
    noFree: (coach: string, day: string) => `Nada libre con ${coach} ${day}. Prueba otro día.`,
    notStudent: "Primero tu entrenador tiene que aceptarte; el enlace de su página lo hace.",
    paused: (coach: string) => `Tus reservas con ${coach} están en pausa. Escribe a ${coach}.`,
    whichCoach: "¿Con qué entrenador?",
    left: (coach: string, line: string) => `Con ${coach}: ${line}`,
    lateWarning: (hours: number) => `Menos de ${hours} h antes: un pase gratis o una clase.`,
    youWereAccepted: (coach: string) => `${coach} te aceptó. Reserva cuando quieras: escríbeme un día y una hora, o abre el enlace.`,
    open: "Abrir",
    studentHelp: "Escríbeme un día y una hora para reservar (vie 15), «cancelar vie» para cancelar, «mover vie 15» para moverla, «pagado» cuando hayas pagado, o «quedan» para tu bono.",
    // el menú bajo el campo de texto
    menuToday: "📅 Hoy",
    menuTomorrow: "Mañana",
    menuWeek: "Semana",
    menuLow: "Casi sin clases",
    menuBook: "＋ Reservar",
    menuLessons: "🎾 Mis clases",
    menuLeft: "Bono",
    menuCancel: "✕ Cancelar",
    menuCoach: "Tu asistente. Toca un botón o escribe una línea: anna vie 15 reserva, cancelar anna vie cancela, bloquear sáb deja el día libre.",
    menuStudent: "Tus clases. Toca un botón o escribe un día y una hora: vie 15.",
    menuBookHow: "Nombre, día y hora: anna vie 15. Un nombre nuevo se convierte en alumno nuevo.",
    menuBookHowStudent: "Un día y una hora: vie 15. Solo el día muestra las horas libres.",
    // el enlace desde el botón de la configuración
    coachLinked: "Enlazado. Aquí también soy tu asistente: escríbeme una línea (anna vie 15 reserva, mañana muestra el día, bajo dice a quién se le acaban las clases) y respondo a tus alumnos mientras enseñas.",
    coachOpen: "Abrir mi asistente",
    commandsCoach: [
      { command: "today", description: "Clases de hoy" },
      { command: "week", description: "La semana" },
      { command: "coach", description: "Abrir mi asistente" },
      { command: "help", description: "Qué hago" },
    ],
    commandsStudent: [
      { command: "lessons", description: "Mis clases y mi bono" },
      { command: "help", description: "Qué hago" },
    ],
    menuPlaceholder: "anna vie 15",
    menuPlaceholderStudent: "vie 15",
    // chains: offers, requests, reminders
    altTimes: "Libre en su lugar:",
    offer: (coach: string, when: string, minutes: number) => `Se ha liberado un hueco con ${coach}: ${when}. Es tuyo durante ${minutes} minutos.`,
    offerTake: "Reservar",
    offerNo: "No, gracias",
    offerTaken: (when: string, pkg: string) => `Reservado: ${when}. ${pkg}`,
    offerGone: "Ese hueco ya no está.",
    offerLapsed: (when: string) => `La oferta de ${when} caducó y pasó al siguiente de la lista. Puedes apuntarte otra vez cuando quieras.`,
    offerWithdrawn: "Fuera de la lista.",
    waitlisted: (when: string) => `En la lista para ${when}. El primer hueco libre es tuyo durante 30 minutos.`,
    waitlistedWeek: (week: string) => `En la lista para la semana del ${week}. El primer hueco libre es tuyo durante 30 minutos.`,
    requestSent: (coach: string, when: string) => `Pedido a ${coach}: ${when}, fuera del horario habitual. La respuesta llega aquí.`,
    requestAsk: (name: string, when: string) => `${name} pide ${when}, fuera de tu horario.`,
    requestYes: "Sí",
    requestNo: "No",
    requestAccepted: (coach: string, when: string, pkg: string) => `${coach} ha dicho que sí: ${when}. ${pkg}`,
    requestDeclined: (coach: string, when: string) => `${coach} no puede ${when}. Elige otra hora.`,
    requestAnswered: (name: string, yes: boolean) => (yes ? `Reservado: ${name}.` : `${name} recibe un no.`),
    requestGone: "Ya respondido.",
    reminder: (coach: string, when: string, pkg: string) => `Mañana: ${when} con ${coach}. ${pkg}`,
    lowPackage: (coach: string, line: string) => `Con ${coach}: ${line} ¿Hora del siguiente bono?`,
    managerJoined: (name: string) => `${name} ahora lleva tu agenda contigo.`,
    waiting: (n: number) => `${n} esperando un hueco.`,
    // toques: cada paso de la agenda es un botón; se escribe solo un nombre o una cifra
    tapWho: "¿Para quién es la clase?",
    tapNewStudent: "＋ Alumno nuevo",
    tapAskName: "¿Cómo se llama?",
    tapWhichDay: (name: string) => `${name}: ¿qué día?`,
    tapWhichDayStudent: (coach: string) => `Una clase con ${coach}: ¿qué día?`,
    tapHowLong: "¿Cuánto dura?",
    tapWhichTime: (day: string) => `${day}: ¿a qué hora?`,
    tapOtherTime: "✎ Otra hora",
    tapAskTime: (day: string) => `${day}: ¿a qué hora? Escríbela así: 15:30.`,
    tapBadTime: "No entiendo esa hora. Escríbela así: 15:30.",
    tapHowMany: "¿Cuántos vienen?",
    tapNoFree: (day: string) => `Nada libre ${day}.`,
    tapWaitWeek: "🔔 Avísame si se libera un hueco esa semana",
    tapAskAnother: "❓ Pedir otra hora",
    tapAskAnotherTime: (day: string) => `${day}: ¿a qué hora te gustaría? Escríbela así: 19:30. Tu entrenador dice sí o no.`,
    tapBack: "‹ Atrás",
    tapKeep: "Dejarla",
    tapCancelAsk: (name: string, when: string) => `¿Cancelar ${name}, ${when}?`,
    tapCancelYes: "✕ Sí, cancelar",
    tapWhichLesson: "¿Qué clase?",
    tapMoveWhere: (name: string, when: string) => `${name}, ${when}: ¿a qué día la movemos?`,
    tapNothingAhead: "Nada reservado en las próximas dos semanas.",
    tapLesson: (name: string, when: string, pkg: string, money: string) => `${name} · ${when}
${pkg}${money ? `
${money}` : ""}`,
    tapMove: "↔ Mover",
    tapCancelBtn: "✕ Cancelar",
    tapNoShow: "👻 No vino",
    tapCame: "↩ Sí vino",
    tapNoShowDone: (name: string, when: string) => `No vino: ${name}, ${when}. La clase cuenta.`,
    tapCameDone: (name: string, when: string) => `${name}, ${when}: al final sí.`,
    tapOnMe: "🎁 Invito yo",
    tapOnMeDone: (name: string, when: string) => `${name}, ${when}: invitas tú. No debe nada.`,
    tapMoneyNotPaid: (amount: string) => `${amount} · sin pagar`,
    tapMoneySaysPaid: (amount: string) => `${amount} · dice que pagó`,
    tapMoneyPaid: (amount: string) => `${amount} · pagado`,
    tapStudents: "Tus alumnos",
    tapStudentsNone: "Aún no hay alumnos. Comparte tu enlace: quien lo abra queda en la lista.",
    tapStudentLine: (name: string, pkg: string, owes: string) => `${name} · ${pkg}${owes ? ` · ${owes}` : ""}`,
    tapOwes: (amount: string) => `debe ${amount}`,
    tapStudentCard: (name: string, pkg: string, owes: string, next: string) => `${name}
${pkg}${owes ? `
${owes}` : ""}
${next}`,
    tapNextLesson: (when: string) => `Próxima: ${when}`,
    tapNoNext: "Nada reservado.",
    tapBookFor: "＋ Reservar",
    tapPackageFor: "＋ Bono",
    tapWhichPackage: (name: string) => `¿Qué bono para ${name}?`,
    tapPackageLabel: (size: number, minutes: number, heads: number, price: string) => `${size} × ${minutes} min${heads > 1 ? ` · ${heads}` : ""} · ${price}`,
    tapPackageCustom: "✎ Otro bono",
    tapAskPackage: (name: string) => `Un bono para ${name}: clases, días y precio, como 10 90d 6000.`,
    tapBadPackage: "Escribe primero las clases, como 10 90d 6000.",
    tapMoney: "Dinero",
    tapMoneyNone: "Nadie te debe nada.",
    tapMoneyPackage: (name: string, size: number, amount: string) => `${name} · bono de ${size} · ${amount}`,
    tapSettingsHow: "Toca para cambiar. Los clubs son lo único que se escribe: club Rawai Padel.",
    tapSettingsWeb: "Precios, bonos y el resto ↗",
    tapStudentWhichCoach: "¿Con qué entrenador?",
    tapPay: "Pagar y bono",
    tapTakePackage: "Coger un bono",
    tapPackages: (coach: string) => `Bonos con ${coach}:`,
    tapPackagesNone: (coach: string) => `${coach} no vende bonos en su página.`,
    tapPackageTaken: (size: number, amount: string, coach: string) => `Tu bono ha empezado: ${size} clases. Paga ${amount} a ${coach}.`,
    tapPayHow: (lines: string) => `Cómo pagar:
${lines}`,
    tapPayAtClub: "En el club, en efectivo o con tarjeta.",
    tapPayPromptpay: "PromptPay: escanea el QR de arriba.",
    tapPayLink: "Pagar por enlace",
    tapPayAsk: (coach: string) => `Pregunta a ${coach} cómo prefiere cobrar.`,
    tapHasPackage: "Ya tienes un bono con clases por usar.",
    tapAskedCoach: (coach: string, when: string) => `Pedido a ${coach}: ${when}. La respuesta llega aquí.`,
    tapEach: (amount: string) => `${amount} cada uno`,
    menuCancelCoach: "✕ Cancelar",
    menuMove: "↔ Mover",
    menuStudents: "👥 Alumnos",
    menuMoney: "💰 Dinero",
    menuSettings: "⚙️ Ajustes",
    menuPay: "💳 Pagar y bono",
    // cifras y horas con toques: un teclado en el chat, horas y minutos como botones
    tapKeypadOk: "✓ Listo",
    tapEnter: (label: string, digits: string) => `${label}: ${digits || "…"}`,
    tapPairEach: "Pareja, cada uno",
    tapSecondLength: "Segunda duración",
    tapSecondOne: "Segunda duración, una persona",
    tapSecondPair: "Segunda duración, pareja cada uno",
    tapFee: "Extra fuera de tu horario",
    tapNone: "Ninguna",
    tapOffersTitle: "Bonos en tu página",
    tapOffersNone: "Aún no hay bonos en tu página. Los alumnos eligen uno allí con un toque.",
    tapOfferAdd: "＋ Añadir un bono",
    tapHowManyLessons: "¿Cuántas clases?",
    tapValidFor: "¿Válido cuánto tiempo?",
    tapNoExpiry: "Sin caducidad",
    tapForHowMany: "¿Para cuántos en pista?",
    tapPriceEach: (hint: string) => `Precio, cada uno${hint ? ` (${hint})` : ""}`,
    tapWhichHour: "¿Qué hora?",
    tapWhichMinute: (hour: string) => `${hour}: ¿y los minutos?`,
    tapDays: (n: number) => `${n} d`,
    menuBlock: "🚫 Bloquear tiempo",
    tapBlockDay: "¿Qué día bloqueamos?",
    tapBlockWhat: (day: string) => `${day}: ¿qué bloqueamos?`,
    tapAllDay: "Todo el día",
    menuCoachTaps: "Tu asistente. Toca un botón: reservar, cancelar, mover, bloquear, alumnos, dinero, ajustes. Todo son toques; solo escribes un nombre o un precio.",
    menuStudentTaps: "Tus clases. Toca un botón: reservar, mover, cancelar, pagar. Solo escribes una hora.",
  },
} as const;

export type CoachBotStrings = (typeof S)[CoachBotLocale];
export const coachStrings = (locale: CoachBotLocale): CoachBotStrings => S[locale];

/** "Fri 12 Sep 15:00" in the coach's zone and the reader's language. */
export function whenLabel(at: Date, tz: string, locale: string): string {
  const day = new Intl.DateTimeFormat(locale, { weekday: "short", day: "numeric", month: "short", timeZone: tz }).format(at);
  const time = new Intl.DateTimeFormat(locale, { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: tz }).format(at);
  return `${day} ${time}`;
}

export function dayOnlyLabel(dateStr: string, locale: string): string {
  return new Intl.DateTimeFormat(locale, { weekday: "short", day: "numeric", month: "short", timeZone: "UTC" }).format(new Date(`${dateStr}T00:00:00Z`));
}
